/// 
/// DepartmentGroup
/// 
/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
///
using Microsoft.AspNetCore.Mvc;
using SampleSinglePageApplication.EFModels.EFModels;

namespace SampleSinglePageApplication.Web.Controllers
{
	public partial class DataController : ControllerBase
	{

		[HttpGet]
		[Route("~/api/Data/GetDepartmentGroupAuto/{departmentGroupId}")]
		public async Task<ActionResult<DataObjects.DepartmentGroup>> GetDepartmentGroupAuto(Guid departmentGroupId)
		{
			DataObjects.DepartmentGroup? output = null;

			if (CurrentUser.Admin) {
				output = await da.GetDepartmentGroupAuto(departmentGroupId);
				if (output != null && output.TenantId == CurrentUser.TenantId) {
				    return Ok(output);
				} else {
				    return Unauthorized("Access Denied");
				}
			} else {
				return Unauthorized("Access Denied");
			}
		}

		[HttpPost]
		[Route("~/api/Data/GetDepartmentGroupsFilteredAuto/")]
		public async Task<ActionResult<DataObjects.FilterDepartmentGroupsAuto>> GetDepartmentGroupsFilteredAuto(DataObjects.FilterDepartmentGroupsAuto filter)
		{
			if (CurrentUser.Admin) {
				filter.TenantId = CurrentUser.TenantId;
				var output = await da.GetDepartmentGroupsFilteredAuto(filter);
				return Ok(output);
			} else {
				return Unauthorized("Access Denied");
			}
		}

		[HttpGet]
		[Route("~/api/Data/DeleteDepartmentGroupAuto/{departmentGroupId}")]
		public async Task<ActionResult<bool>> DeleteDepartmentGroupAuto(Guid departmentGroupId)
		{
			if (CurrentUser.Admin) {
				var existing = await da.GetDepartmentGroupAuto(departmentGroupId);
				if (existing != null && existing.TenantId == CurrentUser.TenantId) {
					var output = await da.DeleteDepartmentGroupAuto(departmentGroupId);
					return Ok(output);
			} else {
					return Unauthorized("Access Denied");
			}
			} else {
				return Unauthorized("Access Denied");
			}
		}

		[HttpPost]
		[Route("~/api/Data/SaveDepartmentGroupAuto/")]
		public async Task<ActionResult<DataObjects.DepartmentGroup>> SaveDepartmentGroupAuto(DataObjects.DepartmentGroup departmentGroup)
		{
            DataObjects.DepartmentGroup output = new DataObjects.DepartmentGroup();

            departmentGroup.TenantId = CurrentUser.TenantId;
            if (CurrentUser.Admin) {
				output = await da.SaveDepartmentGroupAuto(departmentGroup);
				return Ok(output);
            } else {
				return Unauthorized("Access Denied");
            }
		}
    }
}
