/// 
/// Setting
/// 
/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
///
using Microsoft.AspNetCore.Mvc;
using SampleSinglePageApplication.EFModels.EFModels;

namespace SampleSinglePageApplication.Web.Controllers
{
	public partial class DataController : ControllerBase
	{

		[HttpGet]
		[Route("~/api/Data/GetSettingAuto/{settingId}")]
		public async Task<ActionResult<DataObjects.Setting>> GetSettingAuto(Int32 settingId)
		{
			DataObjects.Setting? output = null;

			if (CurrentUser.Admin) {
				output = await da.GetSettingAuto(settingId);
				if (output != null && output.TenantId == CurrentUser.TenantId) {
				    return Ok(output);
				} else {
				    return Unauthorized("Access Denied");
				}
			} else {
				return Unauthorized("Access Denied");
			}
		}

		[HttpPost]
		[Route("~/api/Data/GetSettingsFilteredAuto/")]
		public async Task<ActionResult<DataObjects.FilterSettingsAuto>> GetSettingsFilteredAuto(DataObjects.FilterSettingsAuto filter)
		{
			if (CurrentUser.Admin) {
				filter.TenantId = CurrentUser.TenantId;
				var output = await da.GetSettingsFilteredAuto(filter);
				return Ok(output);
			} else {
				return Unauthorized("Access Denied");
			}
		}

		[HttpGet]
		[Route("~/api/Data/DeleteSettingAuto/{settingId}")]
		public async Task<ActionResult<bool>> DeleteSettingAuto(Int32 settingId)
		{
			if (CurrentUser.Admin) {
				var existing = await da.GetSettingAuto(settingId);
				if (existing != null && existing.TenantId == CurrentUser.TenantId) {
					var output = await da.DeleteSettingAuto(settingId);
					return Ok(output);
			} else {
					return Unauthorized("Access Denied");
			}
			} else {
				return Unauthorized("Access Denied");
			}
		}

		[HttpPost]
		[Route("~/api/Data/SaveSettingAuto/")]
		public async Task<ActionResult<DataObjects.Setting>> SaveSettingAuto(DataObjects.Setting setting)
		{
            DataObjects.Setting output = new DataObjects.Setting();

            setting.TenantId = CurrentUser.TenantId;
            if (CurrentUser.Admin) {
				output = await da.SaveSettingAuto(setting);
				return Ok(output);
            } else {
				return Unauthorized("Access Denied");
            }
		}
    }
}
