/// 
/// Tenant
/// 
/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
///
using Microsoft.AspNetCore.Mvc;
using SampleSinglePageApplication.EFModels.EFModels;

namespace SampleSinglePageApplication.Web.Controllers
{
	public partial class DataController : ControllerBase
	{

		[HttpGet]
		[Route("~/api/Data/GetTenantAuto/{tenantId}")]
		public async Task<ActionResult<DataObjects.Tenant>> GetTenantAuto(Guid tenantId)
		{
			DataObjects.Tenant? output = null;

			if (CurrentUser.Admin) {
				output = await da.GetTenantAuto(tenantId);
				if (output != null && output.TenantId == CurrentUser.TenantId) {
				    return Ok(output);
				} else {
				    return Unauthorized("Access Denied");
				}
			} else {
				return Unauthorized("Access Denied");
			}
		}

		[HttpPost]
		[Route("~/api/Data/GetTenantsFilteredAuto/")]
		public async Task<ActionResult<DataObjects.FilterTenantsAuto>> GetTenantsFilteredAuto(DataObjects.FilterTenantsAuto filter)
		{
			if (CurrentUser.Admin) {
				filter.TenantId = CurrentUser.TenantId;
				var output = await da.GetTenantsFilteredAuto(filter);
				return Ok(output);
			} else {
				return Unauthorized("Access Denied");
			}
		}

		[HttpGet]
		[Route("~/api/Data/DeleteTenantAuto/{tenantId}")]
		public async Task<ActionResult<bool>> DeleteTenantAuto(Guid tenantId)
		{
			if (CurrentUser.Admin) {
				var existing = await da.GetTenantAuto(tenantId);
				if (existing != null && existing.TenantId == CurrentUser.TenantId) {
					var output = await da.DeleteTenantAuto(tenantId);
					return Ok(output);
			} else {
					return Unauthorized("Access Denied");
			}
			} else {
				return Unauthorized("Access Denied");
			}
		}

		[HttpPost]
		[Route("~/api/Data/SaveTenantAuto/")]
		public async Task<ActionResult<DataObjects.Tenant>> SaveTenantAuto(DataObjects.Tenant tenant)
		{
            DataObjects.Tenant output = new DataObjects.Tenant();

            tenant.TenantId = CurrentUser.TenantId;
            if (CurrentUser.Admin) {
				output = await da.SaveTenantAuto(tenant);
				return Ok(output);
            } else {
				return Unauthorized("Access Denied");
            }
		}
    }
}
