/// 
/// Department
/// 
/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
///
using Microsoft.AspNetCore.Mvc;
using SampleSinglePageApplication.EFModels.EFModels;

namespace SampleSinglePageApplication.Web.Controllers
{
	public partial class DataController : ControllerBase
	{

		[HttpGet]
		[Route("~/api/Data/GetDepartmentAuto/{departmentId}")]
		public async Task<ActionResult<DataObjects.Department>> GetDepartmentAuto(Guid departmentId)
		{
			DataObjects.Department? output = null;

			if (CurrentUser.Admin) {
				output = await da.GetDepartmentAuto(departmentId);
				if (output != null && output.TenantId == CurrentUser.TenantId) {
				    return Ok(output);
				} else {
				    return Unauthorized("Access Denied");
				}
			} else {
				return Unauthorized("Access Denied");
			}
		}

		[HttpPost]
		[Route("~/api/Data/GetDepartmentsFilteredAuto/")]
		public async Task<ActionResult<DataObjects.FilterDepartmentsAuto>> GetDepartmentsFilteredAuto(DataObjects.FilterDepartmentsAuto filter)
		{
			if (CurrentUser.Admin) {
				filter.TenantId = CurrentUser.TenantId;
				var output = await da.GetDepartmentsFilteredAuto(filter);
				return Ok(output);
			} else {
				return Unauthorized("Access Denied");
			}
		}

		[HttpGet]
		[Route("~/api/Data/DeleteDepartmentAuto/{departmentId}")]
		public async Task<ActionResult<bool>> DeleteDepartmentAuto(Guid departmentId)
		{
			if (CurrentUser.Admin) {
				var existing = await da.GetDepartmentAuto(departmentId);
				if (existing != null && existing.TenantId == CurrentUser.TenantId) {
					var output = await da.DeleteDepartmentAuto(departmentId);
					return Ok(output);
			} else {
					return Unauthorized("Access Denied");
			}
			} else {
				return Unauthorized("Access Denied");
			}
		}

		[HttpPost]
		[Route("~/api/Data/SaveDepartmentAuto/")]
		public async Task<ActionResult<DataObjects.Department>> SaveDepartmentAuto(DataObjects.Department department)
		{
            DataObjects.Department output = new DataObjects.Department();

            department.TenantId = CurrentUser.TenantId;
            if (CurrentUser.Admin) {
				output = await da.SaveDepartmentAuto(department);
				return Ok(output);
            } else {
				return Unauthorized("Access Denied");
            }
		}
    }
}
