/// 
/// Department
/// 
/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
///
class DepartmentsModelAuto {
	MainModel: KnockoutObservable<MainModel> = ko.observable(window.mainModel);
	Filter: KnockoutObservable<filterDepartmentsAuto> = ko.observable(new filterDepartmentsAuto);
	Department: KnockoutObservable<department> = ko.observable(new department);
	Departments: KnockoutObservableArray<department> = ko.observableArray([]);
	Loading: KnockoutObservable<boolean> = ko.observable(false);
	ConfirmDeleteDepartment: KnockoutObservable<string> = ko.observable("");
	ShowDepartmentDetails: KnockoutObservable<boolean> = ko.observable(false);
	FilterViewDepartmentType: KnockoutObservable<string> = ko.observable("list");
	GettingSavedDepartmentFilterName: KnockoutObservable<boolean> = ko.observable(false);
	SavedDepartmentFilterName: KnockoutObservable<string> = ko.observable("");

	constructor() {
		this.MainModel().View.subscribe(() => {
			this.ViewChanged();
		});

		this.MainModel().SignalRUpdate.subscribe(() => {
			this.SignalrUpdate();
		});
		//setTimeout("setupUserPhotoDropZone()", 0);
		setTimeout(() => this.StartFilterMonitoring(), 1000);
	}
	//TODO: click: DeleteSavedDepartmentFilter
	DeleteSavedDepartmentFilter(): void {
		this.MainModel().Message_Hide();
		let filterId: string = this.Filter().filterId();
		
		let success: Function = (data: server.booleanResponse) => {
			this.MainModel().Message_Hide();
			
			if (data != null) {
				if (data.result) {
					let existing: savedFilterDepartmentsAuto = ko.utils.arrayFirst(this.MainModel().User().savedFiltersDepartmentsAuto(), function (item) {
						return item.savedFilterId() == filterId;
					});
					if (existing != null) {
						this.MainModel().User().savedFiltersDepartmentsAuto.remove(existing);
					}
					
					this.ClearDepartmentFilter();
				} else {
					this.MainModel().Message_Errors(data.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to delete the saved filter.");
			}
		};
		
		this.MainModel().Message_Deleting();
		tsUtilities.AjaxData(window.baseURL + "api/Data/DeleteSavedDepartmentFilter/" + filterId.toString(), null, success);
	}
	//TODO: click: ExportDepartment
	ExportDepartments(): void {
		let filter: filterDepartmentsAuto = new filterDepartmentsAuto;
		filter.Load(JSON.parse(ko.toJSON(this.Filter)));
		filter.records([]);
		$("#department-filter").val(ko.toJSON(filter));
		$("#department-filter-download").submit();
	}

	ToggleDepartmentDetails(): void {
		if (this.ShowDepartmentDetails()) {
			this.ShowDepartmentDetails(false);
			localStorage.setItem("department-details-" + this.MainModel().TenantId(), "0");
		} else {
			this.ShowDepartmentDetails(true);
			localStorage.setItem("department-details-" + this.MainModel().TenantId(), "1");
		}
	
		this.RenderDepartmentTable();
	}
	
	/**
	 * Called when the Show or Hide Filter buttons are clicked.
	 */
	ToggleShowDepartmentFilter(): void {
		this.Filter().showFilters(!this.Filter().showFilters());
		this.SaveDepartmentFilter();
	}
	ToggleDepartmentView(): void {
		if (this.FilterViewDepartmentType() == "list") {
			this.FilterViewDepartmentType("card");
		} else {
			this.FilterViewDepartmentType("list");
		}
		localStorage.setItem("department-view-" + this.MainModel().TenantId(), this.FilterViewDepartmentType());
		this.RenderDepartmentTable();
	}
	SaveDepartmentFilterRecord(): void {
		if (!tsUtilities.HasValue(this.SavedDepartmentFilterName())) {
			tsUtilities.DelayedFocus("saved-department-filter-name");
			return;
		}
		
		let success: Function = (data: server.savedFilterDepartmentsAuto) => {
			this.MainModel().Message_Hide();
			
			if (data != null) {
				if (data.actionResponse.result) {
					let existing: savedFilterDepartmentsAuto = null;
					
					if (this.MainModel().User().savedFiltersDepartmentsAuto() != null && this.MainModel().User().savedFiltersDepartmentsAuto().length > 0) {
						existing = ko.utils.arrayFirst(this.MainModel().User().savedFiltersDepartmentsAuto(), function (item) {
							return item.savedFilterId() == data.savedFilterId;
						});
					}
					
					if (existing != null) {
						existing.Load(data);
					} else {
						let newSavedFilter: savedFilterDepartmentsAuto = new savedFilterDepartmentsAuto();
						newSavedFilter.Load(data);
						this.MainModel().User().savedFiltersDepartmentsAuto.push(newSavedFilter);
					}
					
					this.MainModel().User().savedFiltersDepartmentsAuto.sort(function (l, r) {
						return l.description() > r.description() ? 1 : -1;
					});
					
					this.GettingSavedDepartmentFilterName(false);
				} else {
					this.MainModel().Message_Errors(data.actionResponse.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to save the filter.");
			}
		};
		this.Filter().tenantId(this.MainModel().TenantId());
		
		let f: filterDepartmentsAuto = new filterDepartmentsAuto();
		f.Load(JSON.parse(ko.toJSON(this.Filter)));
		f.columns(null);
		f.records(null);
		
		let postFilter: savedFilterDepartmentsAuto = new savedFilterDepartmentsAuto();
		postFilter.description(this.SavedDepartmentFilterName());
		postFilter.savedFilterId(this.Filter().filterId());
		postFilter.userId(this.MainModel().User().userId());
		postFilter.tenantId(this.MainModel().TenantId());
		postFilter.filter(f);
		
		this.MainModel().Message_Saving();
		tsUtilities.AjaxData(window.baseURL + "api/Data/SaveSavedDepartmentFilter", ko.toJSON(postFilter), success);
	}
	/**
	 * Method fires when the URL action is "NewDepartment"
	 */
	AddDepartment(): void {
		this.Department(new department);
		this.Department().departmentId(this.MainModel().GuidEmpty());
		this.Department().tenantId(this.MainModel().TenantId());
	
		//this.MainModel().UDFFieldsRender("edit-department-udf-fields", "Departments", JSON.parse(ko.toJSON(this.Department)));
	
		tsUtilities.DelayedFocus("edit-department-departmentid");
	}
	
	/**
	 * Clears the values for the department search filter.
	 */
	ClearDepartmentFilter(): void {
	
		this.Loading(true);
	
		this.Filter().keyword(null);
		this.Filter().departmentId(null);
		this.Filter().departmentName(null);
		this.Filter().departmentNameFilterExact(false);
		this.Filter().activeDirectoryNames(null);
		this.Filter().activeDirectoryNamesFilterExact(false);
		this.Filter().enabled(null);
		this.Filter().departmentGroupId(null);
		this.Filter().udf01(null);
		this.Filter().udf02(null);
		this.Filter().udf03(null);
		this.Filter().udf04(null);
		this.Filter().udf05(null);
		this.Filter().udf06(null);
		this.Filter().udf07(null);
		this.Filter().udf08(null);
		this.Filter().udf09(null);
		this.Filter().udf10(null);
		this.Filter().page(1);
	
		//TODO: Callback method for more filtering outside of the autos
	
		this.Loading(false);
		this.GetDepartments();
	}
	
	/**
	 * Deletes a department.
	 */
	DeleteDepartment(): void {
		let success: Function = (data: server.booleanResponse) => {
			this.MainModel().Message_Hide();
			if (data != null) {
				if (data.result) {
					this.MainModel().Nav("DepartmentsAuto");
				} else {
					this.MainModel().Message_Errors(data.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to delete the Department.");
			}
		};
	
		this.MainModel().Message_Deleting();
		tsUtilities.AjaxData(window.baseURL + "api/Data/DeleteDepartmentAuto/" + this.MainModel().Id(), null, success);
	}
	
	/**
	 * Method fires when the URL action is "EditDepartment"
	 */
	EditDepartment(): void {
		this.MainModel().Message_Hide();
		let departmentId: string = this.MainModel().Id();
		this.Department(new department);
		this.Department().departmentId(null);
	
		if (tsUtilities.HasValue(departmentId)) {
			let success: Function = (data: server.department) => {
				if (data != null) {
					if (data.actionResponse.result) {
						this.Department().Load(data);
						tsUtilities.DelayedFocus("edit-department-category");
	
						//this.MainModel().UDFFieldsRender("edit-department-udf-fields", "Departments", JSON.parse(ko.toJSON(this.Department)));
	
						this.Loading(false);
					} else {
						this.MainModel().Message_Errors(data.actionResponse.messages);
					}
				} else {
					this.MainModel().Message_Error("An unknown error occurred attempting to load the Department record.");
				}
			};
	
			this.Loading(true);
			tsUtilities.AjaxData(window.baseURL + "api/data/GetDepartmentAuto/" + departmentId, null, success);
		} else {
			this.MainModel().Message_Error("No valid DepartmentId received.");
		}
	
	}
	
	/**
	 * The callback method used by the paged recordset control to handle the action on the record.
	 * @param record {server.department} - The object being passed is a JSON object, not an observable.
	 */
	EditDepartmentCallback(record: server.department): void {
		if (record != undefined && record != null && tsUtilities.HasValue(record.departmentId)) {
			this.MainModel().Nav("EditDepartmentAuto", record.departmentId);
		}
	}
	
	/**
	 * Called when the department filter changes to reload department records, unless the filter is changing because
	 * records are being reloaded.
	 */
	FilterChanged(): void {
		if (!this.Loading()) {
			this.GetDepartments();
		}
	}
	
	/**
	 * Loads the saved filter that is stored in a cookie as a JSON object.
	 */
	GetSavedFilter(): void {
		this.Filter(new filterDepartmentsAuto);
		this.Filter().tenantId(this.MainModel().TenantId());
	
		// maybe this should be specific per tenant?
		let savedFilter: string = localStorage.getItem("saved-filter-departments-" + this.MainModel().TenantId().toLowerCase());
		if (tsUtilities.HasValue(savedFilter)) {
			this.Filter().Load(JSON.parse(savedFilter));
			this.StartFilterMonitoring();
		}
	
		this.GetDepartments();
	}
	
	/**
	 * Called when the filter changes or when the page loads to get the departments matching the current filter.
	 */
	GetDepartments(): void {
		// Load the filter
		this.Loading(true);
		if (this.Filter().recordsPerPage() == null || this.Filter().recordsPerPage() == 0) {
			this.Filter().recordsPerPage(10);
		}
	
		let success: Function = (data: server.filterDepartmentsAuto) => {
			this.MainModel().Message_Hide();
			if (data != null) {
				if (data.actionResponse.result) {
					this.Filter().Load(data);
	
					this.RenderDepartmentTable();
	
					this.Loading(false);
				} else {
					this.MainModel().Message_Errors(data.actionResponse.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to load Department records.");
			}
			this.Loading(false);
		};
	
	
		let postFilter: filterDepartmentsAuto = new filterDepartmentsAuto();
		postFilter.Load(JSON.parse(ko.toJSON(this.Filter)));
		postFilter.columns(null);
		postFilter.records(null);
	
		let jsonData: string = ko.toJSON(postFilter);
		localStorage.setItem("saved-filter-departments-" + this.MainModel().TenantId().toLowerCase(), jsonData);
		tsUtilities.AjaxData(window.baseURL + "api/Data/GetDepartmentsFilteredAuto/", jsonData, success);
	
	}
	
	/**
	 * Method handles the callback from the paged recordset control when the page changes, the records per page changes, or when the sort order changes.
	 * @param type {string} - The type of change event (count, page, or sort)
	 * @param data {any} - The data passed back, which is a number for count and page and a field column id for the sort.
	 */
	RecordsetCallbackHandler(type: string, data: any): void {
		console.log("RecordsetCallbackHandler", type, data);
		switch (type) {
			case "count":
				window.departmentsModelAuto.Filter().recordsPerPage(data);
				window.departmentsModelAuto.GetDepartments();
				break;
	
			case "page":
				window.departmentsModelAuto.Filter().page(data);
				window.departmentsModelAuto.GetDepartments();
				break;
	
			case "sort":
				window.departmentsModelAuto.UpdateSort(data);
				break;
		}
	}
	
	/**
	 * Called when the Refresh Filter button is clicked.
	 */
	RefreshDepartmentFilter(): void {
		this.SaveDepartmentFilter();
		this.GetDepartments();
	}
	
	/**
	 * Renders the paged recordset view. This happens when the filter loads, but also gets called for certain SignalR events
	 * to update departments that might be in the current department list.
	 */
	RenderDepartmentTable(): void {
		// Load records in the pagedRecordset
		let f: filter = new filter();
		f.Load(JSON.parse(ko.toJSON(this.Filter)));
	
		let records: any = JSON.parse(ko.toJSON(this.Filter().records));
	
		pagedRecordset.Render({
			elementId: "department-records-auto",
			data: JSON.parse(ko.toJSON(f)),
			recordsetCallbackHandler: (type: string, data: any) => { this.RecordsetCallbackHandler(type, data); },
			actionHandlers: [
				{
					callbackHandler: (department: server.department) => { this.EditDepartmentCallback(department); },
					actionElement: "<button type='button' class='btn btn-sm btn-primary nowrap'>" + this.MainModel().IconAndText("Department.EditTableButton") + "</button>"
				}
			],
			recordNavigation: "both",
			//photoBaseUrl: photoBaseUrl,
			booleanIcon: this.MainModel().Icon("selected")
		});
	}
	
	/**
	 * Saves the current filter as a JSON object in a cookie. The items that aren't needed are nulled out first
	 * so that the column data and record data are not stored in the cookie.
	 */
	SaveDepartmentFilter(): void {
		let saveFilter: filterDepartmentsAuto = new filterDepartmentsAuto();
		saveFilter.Load(JSON.parse(ko.toJSON(this.Filter)));
		saveFilter.actionResponse(null);
		saveFilter.columns([]);
		saveFilter.records(null);
	
		localStorage.setItem("saved-filter-departments-" + this.MainModel().TenantId().toLowerCase(), ko.toJSON(saveFilter));
	}
	
	/**
	 * Saves a department record for the department currently being added or edited.
	 */
	SaveDepartment(): void {
		this.MainModel().Message_Hide();
		let errors: string[] = [];
		let focus: string = "";
	
	
		if (errors.length > 0) {
			this.MainModel().Message_Errors(errors);
			tsUtilities.DelayedFocus(focus);
			return;
		}
	
		this.MainModel().UDFFieldsGetValues("Departments", this.Department());
		let json: string = ko.toJSON(this.Department);
	
		let success: Function = (data: server.department) => {
			this.MainModel().Message_Hide();
			if (data != null) {
				if (data.actionResponse.result) {
					this.MainModel().Nav("DepartmentsAuto");
				} else {
					this.MainModel().Message_Errors(data.actionResponse.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to save this Department.");
			}
		};
	
		this.MainModel().Message_Saving();
		tsUtilities.AjaxData(window.baseURL + "api/Data/SaveDepartmentAuto", json, success);
	}
	
	/**
	 * This model subscribes to SignalR updates from the MainModel so that departments in the department filter list
	 * can be removed or updated when their data changes or they are deleted.
	 */
	SignalrUpdate(): void {
		//console.log("In Tenants, SignalR Update", JSON.parse(ko.toJSON(this.MainModel().SignalRUpdate)));
		switch (this.MainModel().SignalRUpdate().updateTypeString().toLowerCase()) {
			case "setting":
				let departmentId: string = this.MainModel().SignalRUpdate().itemId();
	
				switch (this.MainModel().SignalRUpdate().message().toLowerCase()) {
					case "deleteddepartment":
						let records: any[] = [];
						if (this.Filter().records() != null && this.Filter().records().length > 0) {
							this.Filter().records().forEach(function (e) {
								if (e["departmentId"] != departmentId) {
									records.push(e);
								}
							});
						}
						this.Filter().records(records);
						this.RenderDepartmentTable();
	
						break;
	
					case "saveddepartment":
						let departmentData: any = this.MainModel().SignalRUpdate().object();
	
						let index: number = -1;
						let indexItem: number = -1;
						if (this.Filter().records() != null && this.Filter().records().length > 0) {
							this.Filter().records().forEach(function (e) {
								index++;
								if (e["departmentId"] == departmentId) {
									indexItem = index;
								}
							});
						}
	
						if (indexItem > -1) {
							this.Filter().records()[indexItem] = JSON.parse(departmentData);
							this.RenderDepartmentTable();
						}
				}
	
				break;
		}
	}
	
	/**
	 * Starts observing changes to the filter elements to call FilterChanged when selections are changed.
	 */
	StartFilterMonitoring(): void {
		// Subscribe to filter changed
		this.Filter().keyword.subscribe(() => { this.FilterChanged(); });                                                                                             
		this.Filter().departmentName.subscribe(() => { this.FilterChanged(); });
		this.Filter().departmentNameFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().activeDirectoryNames.subscribe(() => { this.FilterChanged(); });
		this.Filter().activeDirectoryNamesFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().departmentId.subscribe(() => { this.FilterChanged(); });
		this.Filter().tenantId.subscribe(() => { this.FilterChanged(); });
		this.Filter().enabled.subscribe(() => { this.FilterChanged(); });
		this.Filter().departmentGroupId.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf01.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf02.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf03.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf04.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf05.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf06.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf07.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf08.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf09.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf10.subscribe(() => { this.FilterChanged(); });
	}
	
	
	
	/**
	 * Handles changing the sort order and updating the filter.
	 * @param dataElementName
	 */
	UpdateSort(dataElementName: string): void {
		let currentSort: string = this.Filter().sort();
		if (tsUtilities.HasValue(currentSort)) {
			currentSort = currentSort.toLowerCase();
		} else {
			currentSort = "";
		}
	
		let currentDirection: string = this.Filter().sortOrder();
		if (tsUtilities.HasValue(currentDirection)) {
			currentDirection = currentDirection.toUpperCase();
		}
	
		if (tsUtilities.HasValue(dataElementName)) {
			if (currentSort.toLowerCase() == dataElementName.toLowerCase()) {
				if (currentDirection == "ASC") {
					this.Filter().sortOrder("DESC");
				} else {
					this.Filter().sortOrder("ASC");
				}
			} else {
				this.Filter().sort(dataElementName);
				switch (dataElementName.toLowerCase()) {
					case "modified":
						this.Filter().sortOrder("DESC");
						break;
	
					default:
						this.Filter().sortOrder("ASC");
						break;
				}
			}
			this.GetDepartments();
		}
	}
	
	/**
	 * Called when the view changes in the MainModel to do any necessary work in this viewModel.
	 */
	ViewChanged(): void {
		this.Loading(false);
	
		switch (this.MainModel().CurrentView().toLowerCase()) {
			case "editdepartmentauto":
				this.EditDepartment();
				break;
	
			case "newdepartmentauto":
				this.AddDepartment();
				break;
	
			case "departmentsauto":
				this.GetSavedFilter();
				this.Filter().tenantId(this.MainModel().TenantId());
				break;
		}
	}
}
