/// 
/// Tenant
/// 
/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
///
class TenantsModelAuto {
	MainModel: KnockoutObservable<MainModel> = ko.observable(window.mainModel);
	Filter: KnockoutObservable<filterTenantsAuto> = ko.observable(new filterTenantsAuto);
	Tenant: KnockoutObservable<tenant> = ko.observable(new tenant);
	Tenants: KnockoutObservableArray<tenant> = ko.observableArray([]);
	Loading: KnockoutObservable<boolean> = ko.observable(false);
	ConfirmDeleteTenant: KnockoutObservable<string> = ko.observable("");
	ShowTenantDetails: KnockoutObservable<boolean> = ko.observable(false);
	FilterViewTenantType: KnockoutObservable<string> = ko.observable("list");
	GettingSavedTenantFilterName: KnockoutObservable<boolean> = ko.observable(false);
	SavedTenantFilterName: KnockoutObservable<string> = ko.observable("");

	constructor() {
		this.MainModel().View.subscribe(() => {
			this.ViewChanged();
		});

		this.MainModel().SignalRUpdate.subscribe(() => {
			this.SignalrUpdate();
		});
		//setTimeout("setupUserPhotoDropZone()", 0);
		setTimeout(() => this.StartFilterMonitoring(), 1000);
	}
	//TODO: click: DeleteSavedTenantFilter
	DeleteSavedTenantFilter(): void {
		this.MainModel().Message_Hide();
		let filterId: string = this.Filter().filterId();
		
		let success: Function = (data: server.booleanResponse) => {
			this.MainModel().Message_Hide();
			
			if (data != null) {
				if (data.result) {
					let existing: savedFilterTenantsAuto = ko.utils.arrayFirst(this.MainModel().User().savedFiltersTenantsAuto(), function (item) {
						return item.savedFilterId() == filterId;
					});
					if (existing != null) {
						this.MainModel().User().savedFiltersTenantsAuto.remove(existing);
					}
					
					this.ClearTenantFilter();
				} else {
					this.MainModel().Message_Errors(data.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to delete the saved filter.");
			}
		};
		
		this.MainModel().Message_Deleting();
		tsUtilities.AjaxData(window.baseURL + "api/Data/DeleteSavedTenantFilter/" + filterId.toString(), null, success);
	}
	//TODO: click: ExportTenant
	ExportTenants(): void {
		let filter: filterTenantsAuto = new filterTenantsAuto;
		filter.Load(JSON.parse(ko.toJSON(this.Filter)));
		filter.records([]);
		$("#tenant-filter").val(ko.toJSON(filter));
		$("#tenant-filter-download").submit();
	}

	ToggleTenantDetails(): void {
		if (this.ShowTenantDetails()) {
			this.ShowTenantDetails(false);
			localStorage.setItem("tenant-details-" + this.MainModel().TenantId(), "0");
		} else {
			this.ShowTenantDetails(true);
			localStorage.setItem("tenant-details-" + this.MainModel().TenantId(), "1");
		}
	
		this.RenderTenantTable();
	}
	
	/**
	 * Called when the Show or Hide Filter buttons are clicked.
	 */
	ToggleShowTenantFilter(): void {
		this.Filter().showFilters(!this.Filter().showFilters());
		this.SaveTenantFilter();
	}
	ToggleTenantView(): void {
		if (this.FilterViewTenantType() == "list") {
			this.FilterViewTenantType("card");
		} else {
			this.FilterViewTenantType("list");
		}
		localStorage.setItem("tenant-view-" + this.MainModel().TenantId(), this.FilterViewTenantType());
		this.RenderTenantTable();
	}
	SaveTenantFilterRecord(): void {
		if (!tsUtilities.HasValue(this.SavedTenantFilterName())) {
			tsUtilities.DelayedFocus("saved-tenant-filter-name");
			return;
		}
		
		let success: Function = (data: server.savedFilterTenantsAuto) => {
			this.MainModel().Message_Hide();
			
			if (data != null) {
				if (data.actionResponse.result) {
					let existing: savedFilterTenantsAuto = null;
					
					if (this.MainModel().User().savedFiltersTenantsAuto() != null && this.MainModel().User().savedFiltersTenantsAuto().length > 0) {
						existing = ko.utils.arrayFirst(this.MainModel().User().savedFiltersTenantsAuto(), function (item) {
							return item.savedFilterId() == data.savedFilterId;
						});
					}
					
					if (existing != null) {
						existing.Load(data);
					} else {
						let newSavedFilter: savedFilterTenantsAuto = new savedFilterTenantsAuto();
						newSavedFilter.Load(data);
						this.MainModel().User().savedFiltersTenantsAuto.push(newSavedFilter);
					}
					
					this.MainModel().User().savedFiltersTenantsAuto.sort(function (l, r) {
						return l.description() > r.description() ? 1 : -1;
					});
					
					this.GettingSavedTenantFilterName(false);
				} else {
					this.MainModel().Message_Errors(data.actionResponse.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to save the filter.");
			}
		};
		this.Filter().tenantId(this.MainModel().TenantId());
		
		let f: filterTenantsAuto = new filterTenantsAuto();
		f.Load(JSON.parse(ko.toJSON(this.Filter)));
		f.columns(null);
		f.records(null);
		
		let postFilter: savedFilterTenantsAuto = new savedFilterTenantsAuto();
		postFilter.description(this.SavedTenantFilterName());
		postFilter.savedFilterId(this.Filter().filterId());
		postFilter.userId(this.MainModel().User().userId());
		postFilter.tenantId(this.MainModel().TenantId());
		postFilter.filter(f);
		
		this.MainModel().Message_Saving();
		tsUtilities.AjaxData(window.baseURL + "api/Data/SaveSavedTenantFilter", ko.toJSON(postFilter), success);
	}
	/**
	 * Method fires when the URL action is "NewTenant"
	 */
	AddTenant(): void {
		this.Tenant(new tenant);
		this.Tenant().tenantId(this.MainModel().GuidEmpty());
		this.Tenant().tenantId(this.MainModel().TenantId());
	
		//this.MainModel().UDFFieldsRender("edit-tenant-udf-fields", "Tenants", JSON.parse(ko.toJSON(this.Tenant)));
	
		tsUtilities.DelayedFocus("edit-tenant-tenantid");
	}
	
	/**
	 * Clears the values for the tenant search filter.
	 */
	ClearTenantFilter(): void {
	
		this.Loading(true);
	
		this.Filter().keyword(null);
		this.Filter().name(null);
		this.Filter().nameFilterExact(false);
		this.Filter().tenantCode(null);
		this.Filter().tenantCodeFilterExact(false);
		this.Filter().enabled(null);
		this.Filter().udf01(null);
		this.Filter().udf02(null);
		this.Filter().udf03(null);
		this.Filter().udf04(null);
		this.Filter().udf05(null);
		this.Filter().udf06(null);
		this.Filter().udf07(null);
		this.Filter().udf08(null);
		this.Filter().udf09(null);
		this.Filter().udf10(null);
		this.Filter().page(1);
	
		//TODO: Callback method for more filtering outside of the autos
	
		this.Loading(false);
		this.GetTenants();
	}
	
	/**
	 * Deletes a tenant.
	 */
	DeleteTenant(): void {
		let success: Function = (data: server.booleanResponse) => {
			this.MainModel().Message_Hide();
			if (data != null) {
				if (data.result) {
					this.MainModel().Nav("TenantsAuto");
				} else {
					this.MainModel().Message_Errors(data.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to delete the Tenant.");
			}
		};
	
		this.MainModel().Message_Deleting();
		tsUtilities.AjaxData(window.baseURL + "api/Data/DeleteTenantAuto/" + this.MainModel().Id(), null, success);
	}
	
	/**
	 * Method fires when the URL action is "EditTenant"
	 */
	EditTenant(): void {
		this.MainModel().Message_Hide();
		let tenantId: string = this.MainModel().Id();
		this.Tenant(new tenant);
		this.Tenant().tenantId(null);
	
		if (tsUtilities.HasValue(tenantId)) {
			let success: Function = (data: server.tenant) => {
				if (data != null) {
					if (data.actionResponse.result) {
						this.Tenant().Load(data);
						tsUtilities.DelayedFocus("edit-tenant-category");
	
						//this.MainModel().UDFFieldsRender("edit-tenant-udf-fields", "Tenants", JSON.parse(ko.toJSON(this.Tenant)));
	
						this.Loading(false);
					} else {
						this.MainModel().Message_Errors(data.actionResponse.messages);
					}
				} else {
					this.MainModel().Message_Error("An unknown error occurred attempting to load the Tenant record.");
				}
			};
	
			this.Loading(true);
			tsUtilities.AjaxData(window.baseURL + "api/data/GetTenantAuto/" + tenantId, null, success);
		} else {
			this.MainModel().Message_Error("No valid TenantId received.");
		}
	
	}
	
	/**
	 * The callback method used by the paged recordset control to handle the action on the record.
	 * @param record {server.tenant} - The object being passed is a JSON object, not an observable.
	 */
	EditTenantCallback(record: server.tenant): void {
		if (record != undefined && record != null && tsUtilities.HasValue(record.tenantId)) {
			this.MainModel().Nav("EditTenantAuto", record.tenantId);
		}
	}
	
	/**
	 * Called when the tenant filter changes to reload tenant records, unless the filter is changing because
	 * records are being reloaded.
	 */
	FilterChanged(): void {
		if (!this.Loading()) {
			this.GetTenants();
		}
	}
	
	/**
	 * Loads the saved filter that is stored in a cookie as a JSON object.
	 */
	GetSavedFilter(): void {
		this.Filter(new filterTenantsAuto);
		this.Filter().tenantId(this.MainModel().TenantId());
	
		// maybe this should be specific per tenant?
		let savedFilter: string = localStorage.getItem("saved-filter-tenants-" + this.MainModel().TenantId().toLowerCase());
		if (tsUtilities.HasValue(savedFilter)) {
			this.Filter().Load(JSON.parse(savedFilter));
			this.StartFilterMonitoring();
		}
	
		this.GetTenants();
	}
	
	/**
	 * Called when the filter changes or when the page loads to get the tenants matching the current filter.
	 */
	GetTenants(): void {
		// Load the filter
		this.Loading(true);
		if (this.Filter().recordsPerPage() == null || this.Filter().recordsPerPage() == 0) {
			this.Filter().recordsPerPage(10);
		}
	
		let success: Function = (data: server.filterTenantsAuto) => {
			this.MainModel().Message_Hide();
			if (data != null) {
				if (data.actionResponse.result) {
					this.Filter().Load(data);
	
					this.RenderTenantTable();
	
					this.Loading(false);
				} else {
					this.MainModel().Message_Errors(data.actionResponse.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to load Tenant records.");
			}
			this.Loading(false);
		};
	
	
		let postFilter: filterTenantsAuto = new filterTenantsAuto();
		postFilter.Load(JSON.parse(ko.toJSON(this.Filter)));
		postFilter.columns(null);
		postFilter.records(null);
	
		let jsonData: string = ko.toJSON(postFilter);
		localStorage.setItem("saved-filter-tenants-" + this.MainModel().TenantId().toLowerCase(), jsonData);
		tsUtilities.AjaxData(window.baseURL + "api/Data/GetTenantsFilteredAuto/", jsonData, success);
	
	}
	
	/**
	 * Method handles the callback from the paged recordset control when the page changes, the records per page changes, or when the sort order changes.
	 * @param type {string} - The type of change event (count, page, or sort)
	 * @param data {any} - The data passed back, which is a number for count and page and a field column id for the sort.
	 */
	RecordsetCallbackHandler(type: string, data: any): void {
		console.log("RecordsetCallbackHandler", type, data);
		switch (type) {
			case "count":
				window.tenantsModelAuto.Filter().recordsPerPage(data);
				window.tenantsModelAuto.GetTenants();
				break;
	
			case "page":
				window.tenantsModelAuto.Filter().page(data);
				window.tenantsModelAuto.GetTenants();
				break;
	
			case "sort":
				window.tenantsModelAuto.UpdateSort(data);
				break;
		}
	}
	
	/**
	 * Called when the Refresh Filter button is clicked.
	 */
	RefreshTenantFilter(): void {
		this.SaveTenantFilter();
		this.GetTenants();
	}
	
	/**
	 * Renders the paged recordset view. This happens when the filter loads, but also gets called for certain SignalR events
	 * to update tenants that might be in the current tenant list.
	 */
	RenderTenantTable(): void {
		// Load records in the pagedRecordset
		let f: filter = new filter();
		f.Load(JSON.parse(ko.toJSON(this.Filter)));
	
		let records: any = JSON.parse(ko.toJSON(this.Filter().records));
	
		pagedRecordset.Render({
			elementId: "tenant-records-auto",
			data: JSON.parse(ko.toJSON(f)),
			recordsetCallbackHandler: (type: string, data: any) => { this.RecordsetCallbackHandler(type, data); },
			actionHandlers: [
				{
					callbackHandler: (tenant: server.tenant) => { this.EditTenantCallback(tenant); },
					actionElement: "<button type='button' class='btn btn-sm btn-primary nowrap'>" + this.MainModel().IconAndText("Tenant.EditTableButton") + "</button>"
				}
			],
			recordNavigation: "both",
			//photoBaseUrl: photoBaseUrl,
			booleanIcon: this.MainModel().Icon("selected")
		});
	}
	
	/**
	 * Saves the current filter as a JSON object in a cookie. The items that aren't needed are nulled out first
	 * so that the column data and record data are not stored in the cookie.
	 */
	SaveTenantFilter(): void {
		let saveFilter: filterTenantsAuto = new filterTenantsAuto();
		saveFilter.Load(JSON.parse(ko.toJSON(this.Filter)));
		saveFilter.actionResponse(null);
		saveFilter.columns([]);
		saveFilter.records(null);
	
		localStorage.setItem("saved-filter-tenants-" + this.MainModel().TenantId().toLowerCase(), ko.toJSON(saveFilter));
	}
	
	/**
	 * Saves a tenant record for the tenant currently being added or edited.
	 */
	SaveTenant(): void {
		this.MainModel().Message_Hide();
		let errors: string[] = [];
		let focus: string = "";
	
	//if (!tsUtilities.HasValue(this.Tenant().name())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("Tenant.Name")));
	//    if (focus == "") { focus = "edit-tenant-name"; }
	//}
	//if (!tsUtilities.HasValue(this.Tenant().tenantCode())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("Tenant.TenantCode")));
	//    if (focus == "") { focus = "edit-tenant-tenantcode"; }
	//}
	//if (!tsUtilities.HasValue(this.Tenant().enabled())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("Tenant.Enabled")));
	//    if (focus == "") { focus = "edit-tenant-enabled"; }
	//}
	//if (!tsUtilities.HasValue(this.Tenant().departments())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("Tenant.Departments")));
	//    if (focus == "") { focus = "edit-tenant-departments"; }
	//}
	//if (!tsUtilities.HasValue(this.Tenant().departmentGroups())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("Tenant.DepartmentGroups")));
	//    if (focus == "") { focus = "edit-tenant-departmentgroups"; }
	//}
	//if (!tsUtilities.HasValue(this.Tenant().tenantSettings())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("Tenant.TenantSettings")));
	//    if (focus == "") { focus = "edit-tenant-tenantsettings"; }
	//}
	//if (!tsUtilities.HasValue(this.Tenant().udfLabels())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("Tenant.udfLabels")));
	//    if (focus == "") { focus = "edit-tenant-udflabels"; }
	//}
	//if (!tsUtilities.HasValue(this.Tenant().listItems())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("Tenant.ListItems")));
	//    if (focus == "") { focus = "edit-tenant-listitems"; }
	//}
	
		if (errors.length > 0) {
			this.MainModel().Message_Errors(errors);
			tsUtilities.DelayedFocus(focus);
			return;
		}
	
		this.MainModel().UDFFieldsGetValues("Tenants", this.Tenant());
		let json: string = ko.toJSON(this.Tenant);
	
		let success: Function = (data: server.tenant) => {
			this.MainModel().Message_Hide();
			if (data != null) {
				if (data.actionResponse.result) {
					this.MainModel().Nav("TenantsAuto");
				} else {
					this.MainModel().Message_Errors(data.actionResponse.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to save this Tenant.");
			}
		};
	
		this.MainModel().Message_Saving();
		tsUtilities.AjaxData(window.baseURL + "api/Data/SaveTenantAuto", json, success);
	}
	
	/**
	 * This model subscribes to SignalR updates from the MainModel so that tenants in the tenant filter list
	 * can be removed or updated when their data changes or they are deleted.
	 */
	SignalrUpdate(): void {
		//console.log("In Tenants, SignalR Update", JSON.parse(ko.toJSON(this.MainModel().SignalRUpdate)));
		switch (this.MainModel().SignalRUpdate().updateTypeString().toLowerCase()) {
			case "setting":
				let tenantId: string = this.MainModel().SignalRUpdate().itemId();
	
				switch (this.MainModel().SignalRUpdate().message().toLowerCase()) {
					case "deletedtenant":
						let records: any[] = [];
						if (this.Filter().records() != null && this.Filter().records().length > 0) {
							this.Filter().records().forEach(function (e) {
								if (e["tenantId"] != tenantId) {
									records.push(e);
								}
							});
						}
						this.Filter().records(records);
						this.RenderTenantTable();
	
						break;
	
					case "savedtenant":
						let tenantData: any = this.MainModel().SignalRUpdate().object();
	
						let index: number = -1;
						let indexItem: number = -1;
						if (this.Filter().records() != null && this.Filter().records().length > 0) {
							this.Filter().records().forEach(function (e) {
								index++;
								if (e["tenantId"] == tenantId) {
									indexItem = index;
								}
							});
						}
	
						if (indexItem > -1) {
							this.Filter().records()[indexItem] = JSON.parse(tenantData);
							this.RenderTenantTable();
						}
				}
	
				break;
		}
	}
	
	/**
	 * Starts observing changes to the filter elements to call FilterChanged when selections are changed.
	 */
	StartFilterMonitoring(): void {
		// Subscribe to filter changed
		this.Filter().keyword.subscribe(() => { this.FilterChanged(); });                                                                                             
		this.Filter().name.subscribe(() => { this.FilterChanged(); });
		this.Filter().nameFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().tenantCode.subscribe(() => { this.FilterChanged(); });
		this.Filter().tenantCodeFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().tenantId.subscribe(() => { this.FilterChanged(); });
		this.Filter().enabled.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf01.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf02.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf03.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf04.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf05.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf06.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf07.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf08.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf09.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf10.subscribe(() => { this.FilterChanged(); });
	}
	
	
	
	/**
	 * Handles changing the sort order and updating the filter.
	 * @param dataElementName
	 */
	UpdateSort(dataElementName: string): void {
		let currentSort: string = this.Filter().sort();
		if (tsUtilities.HasValue(currentSort)) {
			currentSort = currentSort.toLowerCase();
		} else {
			currentSort = "";
		}
	
		let currentDirection: string = this.Filter().sortOrder();
		if (tsUtilities.HasValue(currentDirection)) {
			currentDirection = currentDirection.toUpperCase();
		}
	
		if (tsUtilities.HasValue(dataElementName)) {
			if (currentSort.toLowerCase() == dataElementName.toLowerCase()) {
				if (currentDirection == "ASC") {
					this.Filter().sortOrder("DESC");
				} else {
					this.Filter().sortOrder("ASC");
				}
			} else {
				this.Filter().sort(dataElementName);
				switch (dataElementName.toLowerCase()) {
					case "modified":
						this.Filter().sortOrder("DESC");
						break;
	
					default:
						this.Filter().sortOrder("ASC");
						break;
				}
			}
			this.GetTenants();
		}
	}
	
	/**
	 * Called when the view changes in the MainModel to do any necessary work in this viewModel.
	 */
	ViewChanged(): void {
		this.Loading(false);
	
		switch (this.MainModel().CurrentView().toLowerCase()) {
			case "edittenantauto":
				this.EditTenant();
				break;
	
			case "newtenantauto":
				this.AddTenant();
				break;
	
			case "tenantsauto":
				this.GetSavedFilter();
				this.Filter().tenantId(this.MainModel().TenantId());
				break;
		}
	}
}
