/// 
/// User
/// 
/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
///
class UsersModelAuto {
	MainModel: KnockoutObservable<MainModel> = ko.observable(window.mainModel);
	Filter: KnockoutObservable<filterUsersAuto> = ko.observable(new filterUsersAuto);
	User: KnockoutObservable<user> = ko.observable(new user);
	Users: KnockoutObservableArray<user> = ko.observableArray([]);
	Loading: KnockoutObservable<boolean> = ko.observable(false);
	ConfirmDeleteUser: KnockoutObservable<string> = ko.observable("");
	ShowUserDetails: KnockoutObservable<boolean> = ko.observable(false);
	FilterViewUserType: KnockoutObservable<string> = ko.observable("list");
	GettingSavedUserFilterName: KnockoutObservable<boolean> = ko.observable(false);
	SavedUserFilterName: KnockoutObservable<string> = ko.observable("");

	constructor() {
		this.MainModel().View.subscribe(() => {
			this.ViewChanged();
		});

		this.MainModel().SignalRUpdate.subscribe(() => {
			this.SignalrUpdate();
		});
		//setTimeout("setupUserPhotoDropZone()", 0);
		setTimeout(() => this.StartFilterMonitoring(), 1000);
	}
	//TODO: click: DeleteSavedUserFilter
	DeleteSavedUserFilter(): void {
		this.MainModel().Message_Hide();
		let filterId: string = this.Filter().filterId();
		
		let success: Function = (data: server.booleanResponse) => {
			this.MainModel().Message_Hide();
			
			if (data != null) {
				if (data.result) {
					let existing: savedFilterUsersAuto = ko.utils.arrayFirst(this.MainModel().User().savedFiltersUsersAuto(), function (item) {
						return item.savedFilterId() == filterId;
					});
					if (existing != null) {
						this.MainModel().User().savedFiltersUsersAuto.remove(existing);
					}
					
					this.ClearUserFilter();
				} else {
					this.MainModel().Message_Errors(data.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to delete the saved filter.");
			}
		};
		
		this.MainModel().Message_Deleting();
		tsUtilities.AjaxData(window.baseURL + "api/Data/DeleteSavedUserFilter/" + filterId.toString(), null, success);
	}
	//TODO: click: ExportUser
	ExportUsers(): void {
		let filter: filterUsersAuto = new filterUsersAuto;
		filter.Load(JSON.parse(ko.toJSON(this.Filter)));
		filter.records([]);
		$("#user-filter").val(ko.toJSON(filter));
		$("#user-filter-download").submit();
	}

	ToggleUserDetails(): void {
		if (this.ShowUserDetails()) {
			this.ShowUserDetails(false);
			localStorage.setItem("user-details-" + this.MainModel().TenantId(), "0");
		} else {
			this.ShowUserDetails(true);
			localStorage.setItem("user-details-" + this.MainModel().TenantId(), "1");
		}
	
		this.RenderUserTable();
	}
	
	/**
	 * Called when the Show or Hide Filter buttons are clicked.
	 */
	ToggleShowUserFilter(): void {
		this.Filter().showFilters(!this.Filter().showFilters());
		this.SaveUserFilter();
	}
	ToggleUserView(): void {
		if (this.FilterViewUserType() == "list") {
			this.FilterViewUserType("card");
		} else {
			this.FilterViewUserType("list");
		}
		localStorage.setItem("user-view-" + this.MainModel().TenantId(), this.FilterViewUserType());
		this.RenderUserTable();
	}
	SaveUserFilterRecord(): void {
		if (!tsUtilities.HasValue(this.SavedUserFilterName())) {
			tsUtilities.DelayedFocus("saved-user-filter-name");
			return;
		}
		
		let success: Function = (data: server.savedFilterUsersAuto) => {
			this.MainModel().Message_Hide();
			
			if (data != null) {
				if (data.actionResponse.result) {
					let existing: savedFilterUsersAuto = null;
					
					if (this.MainModel().User().savedFiltersUsersAuto() != null && this.MainModel().User().savedFiltersUsersAuto().length > 0) {
						existing = ko.utils.arrayFirst(this.MainModel().User().savedFiltersUsersAuto(), function (item) {
							return item.savedFilterId() == data.savedFilterId;
						});
					}
					
					if (existing != null) {
						existing.Load(data);
					} else {
						let newSavedFilter: savedFilterUsersAuto = new savedFilterUsersAuto();
						newSavedFilter.Load(data);
						this.MainModel().User().savedFiltersUsersAuto.push(newSavedFilter);
					}
					
					this.MainModel().User().savedFiltersUsersAuto.sort(function (l, r) {
						return l.description() > r.description() ? 1 : -1;
					});
					
					this.GettingSavedUserFilterName(false);
				} else {
					this.MainModel().Message_Errors(data.actionResponse.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to save the filter.");
			}
		};
		this.Filter().tenantId(this.MainModel().TenantId());
		
		let f: filterUsersAuto = new filterUsersAuto();
		f.Load(JSON.parse(ko.toJSON(this.Filter)));
		f.columns(null);
		f.records(null);
		
		let postFilter: savedFilterUsersAuto = new savedFilterUsersAuto();
		postFilter.description(this.SavedUserFilterName());
		postFilter.savedFilterId(this.Filter().filterId());
		postFilter.userId(this.MainModel().User().userId());
		postFilter.tenantId(this.MainModel().TenantId());
		postFilter.filter(f);
		
		this.MainModel().Message_Saving();
		tsUtilities.AjaxData(window.baseURL + "api/Data/SaveSavedUserFilter", ko.toJSON(postFilter), success);
	}
	/**
	 * Method fires when the URL action is "NewUser"
	 */
	AddUser(): void {
		this.User(new user);
		this.User().userId(this.MainModel().GuidEmpty());
		this.User().tenantId(this.MainModel().TenantId());
	
		//this.MainModel().UDFFieldsRender("edit-user-udf-fields", "Users", JSON.parse(ko.toJSON(this.User)));
	
		tsUtilities.DelayedFocus("edit-user-userid");
	}
	
	/**
	 * Clears the values for the user search filter.
	 */
	ClearUserFilter(): void {
	
		this.Loading(true);
	
		this.Filter().keyword(null);
		this.Filter().userId(null);
		this.Filter().firstName(null);
		this.Filter().firstNameFilterExact(false);
		this.Filter().lastName(null);
		this.Filter().lastNameFilterExact(false);
		this.Filter().email(null);
		this.Filter().emailFilterExact(false);
		this.Filter().phone(null);
		this.Filter().phoneFilterExact(false);
		this.Filter().username(null);
		this.Filter().usernameFilterExact(false);
		this.Filter().employeeId(null);
		this.Filter().employeeIdFilterExact(false);
		this.Filter().departmentId(null);
		this.Filter().title(null);
		this.Filter().titleFilterExact(false);
		this.Filter().location(null);
		this.Filter().locationFilterExact(false);
		this.Filter().enabled(null);
		this.Filter().lastLogin(null);
		this.Filter().lastLoginStart(null);
		this.Filter().lastLoginEnd(null);
		this.Filter().admin(null);
		this.Filter().password(null);
		this.Filter().passwordFilterExact(false);
		this.Filter().preventPasswordChange(null);
		this.Filter().failedLoginAttempts(null);
		this.Filter().lastLockoutDate(null);
		this.Filter().lastLockoutDateStart(null);
		this.Filter().lastLockoutDateEnd(null);
		this.Filter().source(null);
		this.Filter().sourceFilterExact(false);
		this.Filter().udf01(null);
		this.Filter().udf02(null);
		this.Filter().udf03(null);
		this.Filter().udf04(null);
		this.Filter().udf05(null);
		this.Filter().udf06(null);
		this.Filter().udf07(null);
		this.Filter().udf08(null);
		this.Filter().udf09(null);
		this.Filter().udf10(null);
		this.Filter().page(1);
	
		//TODO: Callback method for more filtering outside of the autos
	
		this.Loading(false);
		this.GetUsers();
	}
	
	/**
	 * Deletes a user.
	 */
	DeleteUser(): void {
		let success: Function = (data: server.booleanResponse) => {
			this.MainModel().Message_Hide();
			if (data != null) {
				if (data.result) {
					this.MainModel().Nav("UsersAuto");
				} else {
					this.MainModel().Message_Errors(data.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to delete the User.");
			}
		};
	
		this.MainModel().Message_Deleting();
		tsUtilities.AjaxData(window.baseURL + "api/Data/DeleteUserAuto/" + this.MainModel().Id(), null, success);
	}
	
	/**
	 * Method fires when the URL action is "EditUser"
	 */
	EditUser(): void {
		this.MainModel().Message_Hide();
		let userId: string = this.MainModel().Id();
		this.User(new user);
		this.User().userId(null);
	
		if (tsUtilities.HasValue(userId)) {
			let success: Function = (data: server.user) => {
				if (data != null) {
					if (data.actionResponse.result) {
						this.User().Load(data);
						tsUtilities.DelayedFocus("edit-user-category");
	
						//this.MainModel().UDFFieldsRender("edit-user-udf-fields", "Users", JSON.parse(ko.toJSON(this.User)));
	
						this.Loading(false);
					} else {
						this.MainModel().Message_Errors(data.actionResponse.messages);
					}
				} else {
					this.MainModel().Message_Error("An unknown error occurred attempting to load the User record.");
				}
			};
	
			this.Loading(true);
			tsUtilities.AjaxData(window.baseURL + "api/data/GetUserAuto/" + userId, null, success);
		} else {
			this.MainModel().Message_Error("No valid UserId received.");
		}
	
	}
	
	/**
	 * The callback method used by the paged recordset control to handle the action on the record.
	 * @param record {server.user} - The object being passed is a JSON object, not an observable.
	 */
	EditUserCallback(record: server.user): void {
		if (record != undefined && record != null && tsUtilities.HasValue(record.userId)) {
			this.MainModel().Nav("EditUserAuto", record.userId);
		}
	}
	
	/**
	 * Called when the user filter changes to reload user records, unless the filter is changing because
	 * records are being reloaded.
	 */
	FilterChanged(): void {
		if (!this.Loading()) {
			this.GetUsers();
		}
	}
	
	/**
	 * Loads the saved filter that is stored in a cookie as a JSON object.
	 */
	GetSavedFilter(): void {
		this.Filter(new filterUsersAuto);
		this.Filter().tenantId(this.MainModel().TenantId());
	
		// maybe this should be specific per tenant?
		let savedFilter: string = localStorage.getItem("saved-filter-users-" + this.MainModel().TenantId().toLowerCase());
		if (tsUtilities.HasValue(savedFilter)) {
			this.Filter().Load(JSON.parse(savedFilter));
			this.StartFilterMonitoring();
		}
	
		this.GetUsers();
	}
	
	/**
	 * Called when the filter changes or when the page loads to get the users matching the current filter.
	 */
	GetUsers(): void {
		// Load the filter
		this.Loading(true);
		if (this.Filter().recordsPerPage() == null || this.Filter().recordsPerPage() == 0) {
			this.Filter().recordsPerPage(10);
		}
	
		let success: Function = (data: server.filterUsersAuto) => {
			this.MainModel().Message_Hide();
			if (data != null) {
				if (data.actionResponse.result) {
					this.Filter().Load(data);
	
					this.RenderUserTable();
	
					this.Loading(false);
				} else {
					this.MainModel().Message_Errors(data.actionResponse.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to load User records.");
			}
			this.Loading(false);
		};
	
	
		let postFilter: filterUsersAuto = new filterUsersAuto();
		postFilter.Load(JSON.parse(ko.toJSON(this.Filter)));
		postFilter.columns(null);
		postFilter.records(null);
	
		let jsonData: string = ko.toJSON(postFilter);
		localStorage.setItem("saved-filter-users-" + this.MainModel().TenantId().toLowerCase(), jsonData);
		tsUtilities.AjaxData(window.baseURL + "api/Data/GetUsersFilteredAuto/", jsonData, success);
	
	}
	
	/**
	 * Method handles the callback from the paged recordset control when the page changes, the records per page changes, or when the sort order changes.
	 * @param type {string} - The type of change event (count, page, or sort)
	 * @param data {any} - The data passed back, which is a number for count and page and a field column id for the sort.
	 */
	RecordsetCallbackHandler(type: string, data: any): void {
		console.log("RecordsetCallbackHandler", type, data);
		switch (type) {
			case "count":
				window.usersModelAuto.Filter().recordsPerPage(data);
				window.usersModelAuto.GetUsers();
				break;
	
			case "page":
				window.usersModelAuto.Filter().page(data);
				window.usersModelAuto.GetUsers();
				break;
	
			case "sort":
				window.usersModelAuto.UpdateSort(data);
				break;
		}
	}
	
	/**
	 * Called when the Refresh Filter button is clicked.
	 */
	RefreshUserFilter(): void {
		this.SaveUserFilter();
		this.GetUsers();
	}
	
	/**
	 * Renders the paged recordset view. This happens when the filter loads, but also gets called for certain SignalR events
	 * to update users that might be in the current user list.
	 */
	RenderUserTable(): void {
		// Load records in the pagedRecordset
		let f: filter = new filter();
		f.Load(JSON.parse(ko.toJSON(this.Filter)));
	
		let records: any = JSON.parse(ko.toJSON(this.Filter().records));
	
		pagedRecordset.Render({
			elementId: "user-records-auto",
			data: JSON.parse(ko.toJSON(f)),
			recordsetCallbackHandler: (type: string, data: any) => { this.RecordsetCallbackHandler(type, data); },
			actionHandlers: [
				{
					callbackHandler: (user: server.user) => { this.EditUserCallback(user); },
					actionElement: "<button type='button' class='btn btn-sm btn-primary nowrap'>" + this.MainModel().IconAndText("User.EditTableButton") + "</button>"
				}
			],
			recordNavigation: "both",
			//photoBaseUrl: photoBaseUrl,
			booleanIcon: this.MainModel().Icon("selected")
		});
	}
	
	/**
	 * Saves the current filter as a JSON object in a cookie. The items that aren't needed are nulled out first
	 * so that the column data and record data are not stored in the cookie.
	 */
	SaveUserFilter(): void {
		let saveFilter: filterUsersAuto = new filterUsersAuto();
		saveFilter.Load(JSON.parse(ko.toJSON(this.Filter)));
		saveFilter.actionResponse(null);
		saveFilter.columns([]);
		saveFilter.records(null);
	
		localStorage.setItem("saved-filter-users-" + this.MainModel().TenantId().toLowerCase(), ko.toJSON(saveFilter));
	}
	
	/**
	 * Saves a user record for the user currently being added or edited.
	 */
	SaveUser(): void {
		this.MainModel().Message_Hide();
		let errors: string[] = [];
		let focus: string = "";
	
	//if (!tsUtilities.HasValue(this.User().tenantId())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.TenantId")));
	//    if (focus == "") { focus = "edit-user-tenantid"; }
	//}
	//if (!tsUtilities.HasValue(this.User().displayName())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.DisplayName")));
	//    if (focus == "") { focus = "edit-user-displayname"; }
	//}
	//if (!tsUtilities.HasValue(this.User().username())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.Username")));
	//    if (focus == "") { focus = "edit-user-username"; }
	//}
	//if (!tsUtilities.HasValue(this.User().departmentName())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.DepartmentName")));
	//    if (focus == "") { focus = "edit-user-departmentname"; }
	//}
	//if (!tsUtilities.HasValue(this.User().appAdmin())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.AppAdmin")));
	//    if (focus == "") { focus = "edit-user-appadmin"; }
	//}
	//if (!tsUtilities.HasValue(this.User().photo())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.Photo")));
	//    if (focus == "") { focus = "edit-user-photo"; }
	//}
	//if (!tsUtilities.HasValue(this.User().hasLocalPassword())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.HasLocalPassword")));
	//    if (focus == "") { focus = "edit-user-haslocalpassword"; }
	//}
	//if (!tsUtilities.HasValue(this.User().authToken())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.AuthToken")));
	//    if (focus == "") { focus = "edit-user-authtoken"; }
	//}
	//if (!tsUtilities.HasValue(this.User().tenants())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.Tenants")));
	//    if (focus == "") { focus = "edit-user-tenants"; }
	//}
	//if (!tsUtilities.HasValue(this.User().userTenants())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.UserTenants")));
	//    if (focus == "") { focus = "edit-user-usertenants"; }
	//}
	//if (!tsUtilities.HasValue(this.User().udf01())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.udf01")));
	//    if (focus == "") { focus = "edit-user-udf01"; }
	//}
	//if (!tsUtilities.HasValue(this.User().udf02())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.udf02")));
	//    if (focus == "") { focus = "edit-user-udf02"; }
	//}
	//if (!tsUtilities.HasValue(this.User().udf03())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.udf03")));
	//    if (focus == "") { focus = "edit-user-udf03"; }
	//}
	//if (!tsUtilities.HasValue(this.User().udf04())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.udf04")));
	//    if (focus == "") { focus = "edit-user-udf04"; }
	//}
	//if (!tsUtilities.HasValue(this.User().udf05())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.udf05")));
	//    if (focus == "") { focus = "edit-user-udf05"; }
	//}
	//if (!tsUtilities.HasValue(this.User().udf06())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.udf06")));
	//    if (focus == "") { focus = "edit-user-udf06"; }
	//}
	//if (!tsUtilities.HasValue(this.User().udf07())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.udf07")));
	//    if (focus == "") { focus = "edit-user-udf07"; }
	//}
	//if (!tsUtilities.HasValue(this.User().udf08())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.udf08")));
	//    if (focus == "") { focus = "edit-user-udf08"; }
	//}
	//if (!tsUtilities.HasValue(this.User().udf09())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.udf09")));
	//    if (focus == "") { focus = "edit-user-udf09"; }
	//}
	//if (!tsUtilities.HasValue(this.User().udf10())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.udf10")));
	//    if (focus == "") { focus = "edit-user-udf10"; }
	//}
	//if (!tsUtilities.HasValue(this.User().savedFiltersDepartmentsAuto())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.SavedFiltersDepartmentsAuto")));
	//    if (focus == "") { focus = "edit-user-savedfiltersdepartmentsauto"; }
	//}
	//if (!tsUtilities.HasValue(this.User().savedFiltersDepartmentGroupsAuto())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.SavedFiltersDepartmentGroupsAuto")));
	//    if (focus == "") { focus = "edit-user-savedfiltersdepartmentgroupsauto"; }
	//}
	//if (!tsUtilities.HasValue(this.User().savedFiltersFileStoragesAuto())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.SavedFiltersFileStoragesAuto")));
	//    if (focus == "") { focus = "edit-user-savedfiltersfilestoragesauto"; }
	//}
	//if (!tsUtilities.HasValue(this.User().savedFiltersSettingsAuto())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.SavedFiltersSettingsAuto")));
	//    if (focus == "") { focus = "edit-user-savedfilterssettingsauto"; }
	//}
	//if (!tsUtilities.HasValue(this.User().savedFiltersTenantsAuto())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.SavedFiltersTenantsAuto")));
	//    if (focus == "") { focus = "edit-user-savedfilterstenantsauto"; }
	//}
	//if (!tsUtilities.HasValue(this.User().savedFiltersUsersAuto())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.SavedFiltersUsersAuto")));
	//    if (focus == "") { focus = "edit-user-savedfiltersusersauto"; }
	//}
	//if (!tsUtilities.HasValue(this.User().savedFiltersUserGroupsAuto())) {
	//    errors.push(this.MainModel().MissingRequiredField(this.MainModel().Language("User.SavedFiltersUserGroupsAuto")));
	//    if (focus == "") { focus = "edit-user-savedfiltersusergroupsauto"; }
	//}
	
		if (errors.length > 0) {
			this.MainModel().Message_Errors(errors);
			tsUtilities.DelayedFocus(focus);
			return;
		}
	
		this.MainModel().UDFFieldsGetValues("Users", this.User());
		let json: string = ko.toJSON(this.User);
	
		let success: Function = (data: server.user) => {
			this.MainModel().Message_Hide();
			if (data != null) {
				if (data.actionResponse.result) {
					this.MainModel().Nav("UsersAuto");
				} else {
					this.MainModel().Message_Errors(data.actionResponse.messages);
				}
			} else {
				this.MainModel().Message_Error("An unknown error occurred attempting to save this User.");
			}
		};
	
		this.MainModel().Message_Saving();
		tsUtilities.AjaxData(window.baseURL + "api/Data/SaveUserAuto", json, success);
	}
	
	/**
	 * This model subscribes to SignalR updates from the MainModel so that users in the user filter list
	 * can be removed or updated when their data changes or they are deleted.
	 */
	SignalrUpdate(): void {
		//console.log("In Tenants, SignalR Update", JSON.parse(ko.toJSON(this.MainModel().SignalRUpdate)));
		switch (this.MainModel().SignalRUpdate().updateTypeString().toLowerCase()) {
			case "setting":
				let userId: string = this.MainModel().SignalRUpdate().itemId();
	
				switch (this.MainModel().SignalRUpdate().message().toLowerCase()) {
					case "deleteduser":
						let records: any[] = [];
						if (this.Filter().records() != null && this.Filter().records().length > 0) {
							this.Filter().records().forEach(function (e) {
								if (e["userId"] != userId) {
									records.push(e);
								}
							});
						}
						this.Filter().records(records);
						this.RenderUserTable();
	
						break;
	
					case "saveduser":
						let userData: any = this.MainModel().SignalRUpdate().object();
	
						let index: number = -1;
						let indexItem: number = -1;
						if (this.Filter().records() != null && this.Filter().records().length > 0) {
							this.Filter().records().forEach(function (e) {
								index++;
								if (e["userId"] == userId) {
									indexItem = index;
								}
							});
						}
	
						if (indexItem > -1) {
							this.Filter().records()[indexItem] = JSON.parse(userData);
							this.RenderUserTable();
						}
				}
	
				break;
		}
	}
	
	/**
	 * Starts observing changes to the filter elements to call FilterChanged when selections are changed.
	 */
	StartFilterMonitoring(): void {
		// Subscribe to filter changed
		this.Filter().keyword.subscribe(() => { this.FilterChanged(); });                                                                                             
		this.Filter().lastLogin.subscribe(() => { this.FilterChanged(); });
		this.Filter().lastLoginStart.subscribe(() => { this.FilterChanged(); });
		this.Filter().lastLoginEnd.subscribe(() => { this.FilterChanged(); });
		this.Filter().lastLockoutDate.subscribe(() => { this.FilterChanged(); });
		this.Filter().lastLockoutDateStart.subscribe(() => { this.FilterChanged(); });
		this.Filter().lastLockoutDateEnd.subscribe(() => { this.FilterChanged(); });
		this.Filter().firstName.subscribe(() => { this.FilterChanged(); });
		this.Filter().firstNameFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().lastName.subscribe(() => { this.FilterChanged(); });
		this.Filter().lastNameFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().email.subscribe(() => { this.FilterChanged(); });
		this.Filter().emailFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().phone.subscribe(() => { this.FilterChanged(); });
		this.Filter().phoneFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().username.subscribe(() => { this.FilterChanged(); });
		this.Filter().usernameFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().employeeId.subscribe(() => { this.FilterChanged(); });
		this.Filter().employeeIdFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().title.subscribe(() => { this.FilterChanged(); });
		this.Filter().titleFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().location.subscribe(() => { this.FilterChanged(); });
		this.Filter().locationFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().password.subscribe(() => { this.FilterChanged(); });
		this.Filter().passwordFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().source.subscribe(() => { this.FilterChanged(); });
		this.Filter().sourceFilterExact.subscribe(() => { this.FilterChanged(); });
		this.Filter().userId.subscribe(() => { this.FilterChanged(); });
		this.Filter().tenantId.subscribe(() => { this.FilterChanged(); });
		this.Filter().departmentId.subscribe(() => { this.FilterChanged(); });
		this.Filter().enabled.subscribe(() => { this.FilterChanged(); });
		this.Filter().admin.subscribe(() => { this.FilterChanged(); });
		this.Filter().preventPasswordChange.subscribe(() => { this.FilterChanged(); });
		this.Filter().failedLoginAttempts.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf01.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf02.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf03.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf04.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf05.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf06.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf07.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf08.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf09.subscribe(() => { this.FilterChanged(); });
		this.Filter().udf10.subscribe(() => { this.FilterChanged(); });
	}
	
	
	
	/**
	 * Handles changing the sort order and updating the filter.
	 * @param dataElementName
	 */
	UpdateSort(dataElementName: string): void {
		let currentSort: string = this.Filter().sort();
		if (tsUtilities.HasValue(currentSort)) {
			currentSort = currentSort.toLowerCase();
		} else {
			currentSort = "";
		}
	
		let currentDirection: string = this.Filter().sortOrder();
		if (tsUtilities.HasValue(currentDirection)) {
			currentDirection = currentDirection.toUpperCase();
		}
	
		if (tsUtilities.HasValue(dataElementName)) {
			if (currentSort.toLowerCase() == dataElementName.toLowerCase()) {
				if (currentDirection == "ASC") {
					this.Filter().sortOrder("DESC");
				} else {
					this.Filter().sortOrder("ASC");
				}
			} else {
				this.Filter().sort(dataElementName);
				switch (dataElementName.toLowerCase()) {
					case "modified":
						this.Filter().sortOrder("DESC");
						break;
	
					default:
						this.Filter().sortOrder("ASC");
						break;
				}
			}
			this.GetUsers();
		}
	}
	
	/**
	 * Called when the view changes in the MainModel to do any necessary work in this viewModel.
	 */
	ViewChanged(): void {
		this.Loading(false);
	
		switch (this.MainModel().CurrentView().toLowerCase()) {
			case "edituserauto":
				this.EditUser();
				break;
	
			case "newuserauto":
				this.AddUser();
				break;
	
			case "usersauto":
				this.GetSavedFilter();
				this.Filter().tenantId(this.MainModel().TenantId());
				break;
		}
	}
}
