declare module server {

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	enum settingType { //SampleSinglePageApplication.DataObjects+SettingType
		Boolean = 0,
		DateTime = 1,
		EncryptedText = 2,
		Guid = 3,
		NumberDecimal = 4,
		NumberDouble = 5,
		NumberInt = 6,
		Object = 7,
		Text = 8,
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	enum signalRUpdateType { //SampleSinglePageApplication.DataObjects+SignalRUpdateType
		This = 0,
		That = 1,
		Setting = 2,
		Unknown = 3,
		Files = 4,
		DataMigration = 5,
		Department = 6,
		DepartmentGroup = 7,
		FileStorage = 8,
		Tenant = 9,
		User = 10,
		UserGroup = 11,
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	enum userLookupType { //SampleSinglePageApplication.DataObjects+UserLookupType
		Email = 0,
		EmployeeId = 1,
		Guid = 2,
		Username = 3,
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface actionResponseObject { // SampleSinglePageApplication.DataObjects+ActionResponseObject
		actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface activeDirectorySearchResults { // SampleSinglePageApplication.DataObjects+ActiveDirectorySearchResults
		tenantId: string; //System.Guid: TenantId
		userId: string; //System.Nullable`1[System.Guid]: UserId
		firstName: string; //System.String: FirstName
		lastName: string; //System.String: LastName
		email: string; //System.String: Email
		department: string; //System.String: Department
		location: string; //System.String: Location
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface activeDirectoryUserInfo { // SampleSinglePageApplication.DataObjects+ActiveDirectoryUserInfo
		tenantId: string; //System.Guid: TenantId
		userId: string; //System.Nullable`1[System.Guid]: UserId
		department: string; //System.String: Department
		username: string; //System.String: Username
		firstName: string; //System.String: FirstName
		lastName: string; //System.String: LastName
		email: string; //System.String: Email
		phone: string; //System.String: Phone
		employeeId: string; //System.String: EmployeeId
		title: string; //System.String: Title
		location: string; //System.String: Location
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface addModule { // SampleSinglePageApplication.DataObjects+AddModule
		module: string; //System.String: Module
		name: string; //System.String: Name
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface ajaxLookup extends actionResponseObject { // SampleSinglePageApplication.DataObjects+AjaxLookup
		tenantId: string; //System.Guid: TenantId
		search: string; //System.String: Search
		parameters: string[]; //System.Collections.Generic.List`1[System.String]: Parameters
		results: ajaxResults[]; //SampleSinglePageApplication.DataObjects+AjaxResults: AjaxResults
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface ajaxResults { // SampleSinglePageApplication.DataObjects+AjaxResults
		label: string; //System.String: label
		value: string; //System.String: value
		email: string; //System.String: email
		username: string; //System.String: username
		extra1: string; //System.String: extra1
		extra2: string; //System.String: extra2
		extra3: string; //System.String: extra3
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface applicationSettings extends actionResponseObject { // SampleSinglePageApplication.DataObjects+ApplicationSettings
		applicationURL: string; //System.String: ApplicationURL
		defaultTenantCode: string; //System.String: DefaultTenantCode
		encryptionKey: string; //System.String: EncryptionKey
		mailServer: string; //System.String: MailServer
		mailServerPassword: string; //System.String: MailServerPassword
		mailServerPort: number; //System.Nullable`1[System.Int32]: MailServerPort
		mailServerUsername: string; //System.String: MailServerUsername
		mailServerUseSSL: boolean; //System.Boolean: MailServerUseSSL
		defaultReplyToAddress: string; //System.String: DefaultReplyToAddress
		useTenantCodeInUrl: boolean; //System.Boolean: UseTenantCodeInUrl
		showTenantCodeFieldOnLoginForm: boolean; //System.Boolean: ShowTenantCodeFieldOnLoginForm
		showTenantListingWhenMissingTenantCode: boolean; //System.Boolean: ShowTenantListingWhenMissingTenantCode
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface authenticate { // SampleSinglePageApplication.DataObjects+Authenticate
		username: string; //System.String: Username
		password: string; //System.String: Password
		tenantCode: string; //System.String: TenantCode
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface booleanResponse { // SampleSinglePageApplication.DataObjects+BooleanResponse
		messages: string[]; //System.Collections.Generic.List`1[System.String]: Messages
		result: boolean; //System.Boolean: Result
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface connectionStringConfig extends actionResponseObject { // SampleSinglePageApplication.DataObjects+ConnectionStringConfig
		connectionString: string; //System.String: ConnectionString
		databaseType: string; //System.String: DatabaseType
		mySQL_Server: string; //System.String: MySQL_Server
		mySQL_Database: string; //System.String: MySQL_Database
		mySQL_User: string; //System.String: MySQL_User
		mySQL_Password: string; //System.String: MySQL_Password
		postgreSql_Host: string; //System.String: PostgreSql_Host
		postgreSql_Database: string; //System.String: PostgreSql_Database
		postgreSql_Username: string; //System.String: PostgreSql_Username
		postgreSql_Password: string; //System.String: PostgreSql_Password
		sqLiteDatabase: string; //System.String: SQLiteDatabase
		sqlServer_Server: string; //System.String: SqlServer_Server
		sqlServer_Database: string; //System.String: SqlServer_Database
		sqlServer_UserId: string; //System.String: SqlServer_UserId
		sqlServer_Password: string; //System.String: SqlServer_Password
		sqlServer_IntegratedSecurity: boolean; //System.Boolean: SqlServer_IntegratedSecurity
		sqlServer_PersistSecurityInfo: boolean; //System.Boolean: SqlServer_PersistSecurityInfo
		sqlServer_TrustServerCertificate: boolean; //System.Boolean: SqlServer_TrustServerCertificate
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface dataMigration extends actionResponseObject { // SampleSinglePageApplication.DataObjects+DataMigration
		migration: string[]; //System.Collections.Generic.List`1[System.String]: Migration
		migrationId: string; //System.String: MigrationId
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface department extends actionResponseObject { // SampleSinglePageApplication.DataObjects+Department
		departmentId: string; //System.Guid: DepartmentId
		tenantId: string; //System.Guid: TenantId
		departmentName: string; //System.String: DepartmentName
		activeDirectoryNames: string; //System.String: ActiveDirectoryNames
		enabled: boolean; //System.Boolean: Enabled
		departmentGroupId: string; //System.Nullable`1[System.Guid]: DepartmentGroupId
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface departmentGroup extends actionResponseObject { // SampleSinglePageApplication.DataObjects+DepartmentGroup
		departmentGroupId: string; //System.Guid: DepartmentGroupId
		tenantId: string; //System.Guid: TenantId
		departmentGroupName: string; //System.String: DepartmentGroupName
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface dictionary { // SampleSinglePageApplication.DataObjects+Dictionary
		key: string; //System.String: Key
		value: string; //System.String: Value
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface dropDownEnum { // SampleSinglePageApplication.DataObjects+DropDownEnum
		name: string; //System.String: Name
		value: number; //System.Int32: Value
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface emailMessage extends actionResponseObject { // SampleSinglePageApplication.DataObjects+EmailMessage
		from: string; //System.String: From
		fromDisplayName: string; //System.String: FromDisplayName
		to: string[]; //System.Collections.Generic.List`1[System.String]: To
		cc: string[]; //System.Collections.Generic.List`1[System.String]: Cc
		bcc: string[]; //System.Collections.Generic.List`1[System.String]: Bcc
		subject: string; //System.String: Subject
		body: string; //System.String: Body
		files: fileStorage[]; //SampleSinglePageApplication.DataObjects+FileStorage: FileStorage
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface externalDataSource { // SampleSinglePageApplication.DataObjects+ExternalDataSource
		name: string; //System.String: Name
		type: string; //System.String: Type
		connectionString: string; //System.String: ConnectionString
		source: string; //System.String: Source
		sortOrder: number; //System.Int32: SortOrder
		active: boolean; //System.Boolean: Active
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface fileStorage extends actionResponseObject { // SampleSinglePageApplication.DataObjects+FileStorage
		fileId: string; //System.Guid: FileId
		tenantId: string; //System.Guid: TenantId
		itemId: string; //System.Nullable`1[System.Guid]: ItemId
		fileName: string; //System.String: FileName
		extension: string; //System.String: Extension
		sourceFileId: string; //System.String: SourceFileId
		bytes: number; //System.Nullable`1[System.Int64]: Bytes
		value: any[]; //System.Byte[]: Value
		uploadDate: Date; //System.DateTime: UploadDate
		userId: string; //System.Nullable`1[System.Guid]: UserId
		base64value: string; //System.String: Base64value
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface filter extends actionResponseObject { // SampleSinglePageApplication.DataObjects+Filter
		tenantId: string; //System.Guid: TenantId
		executionTime: number; //System.Double: ExecutionTime
		showFilters: boolean; //System.Boolean: ShowFilters
		start: Date; //System.Nullable`1[System.DateTime]: Start
		end: Date; //System.Nullable`1[System.DateTime]: End
		filterId: string; //System.Nullable`1[System.Guid]: FilterId
		keyword: string; //System.String: Keyword
		sort: string; //System.String: Sort
		sortOrder: string; //System.String: SortOrder
		recordsPerPage: number; //System.Int32: RecordsPerPage
		pageCount: number; //System.Int32: PageCount
		recordCount: number; //System.Int32: RecordCount
		page: number; //System.Int32: Page
		export: any[]; //System.Byte[]: Export
		tenants: string[]; //System.Collections.Generic.List`1[System.Guid]: Tenants
		columns: filterColumn[]; //SampleSinglePageApplication.DataObjects+FilterColumn: FilterColumn
		records: any[]; //System.Object[]: Records
		cultureCode: string; //System.String: CultureCode
		udf01: string; //System.String: udf01
		udf02: string; //System.String: udf02
		udf03: string; //System.String: udf03
		udf04: string; //System.String: udf04
		udf05: string; //System.String: udf05
		udf06: string; //System.String: udf06
		udf07: string; //System.String: udf07
		udf08: string; //System.String: udf08
		udf09: string; //System.String: udf09
		udf10: string; //System.String: udf10
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface filterColumn { // SampleSinglePageApplication.DataObjects+FilterColumn
		align: string; //System.String: Align
		label: string; //System.String: Label
		tipText: string; //System.String: TipText
		dataElementName: string; //System.String: DataElementName
		dataType: string; //System.String: DataType
		sortable: boolean; //System.Boolean: Sortable
		class: string; //System.String: Class
		booleanIcon: string; //System.String: BooleanIcon
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface filterDepartmentGroupsAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+FilterDepartmentGroupsAuto
		departmentGroupId: string; //System.Nullable`1[System.Guid]: DepartmentGroupId
		departmentGroupName: string; //System.String: DepartmentGroupName
		departmentGroupNameFilterExact: boolean; //System.Boolean: DepartmentGroupNameFilterExact
		departmentGroupNameIncludeInKeyword: boolean; //System.Boolean: DepartmentGroupNameIncludeInKeyword
		tenantId: string; //System.Guid: TenantId
		executionTime: number; //System.Double: ExecutionTime
		showFilters: boolean; //System.Boolean: ShowFilters
		start: Date; //System.Nullable`1[System.DateTime]: Start
		end: Date; //System.Nullable`1[System.DateTime]: End
		filterId: string; //System.Nullable`1[System.Guid]: FilterId
		keyword: string; //System.String: Keyword
		sort: string; //System.String: Sort
		sortOrder: string; //System.String: SortOrder
		recordsPerPage: number; //System.Int32: RecordsPerPage
		pageCount: number; //System.Int32: PageCount
		recordCount: number; //System.Int32: RecordCount
		page: number; //System.Int32: Page
		export: any[]; //System.Byte[]: Export
		tenants: string[]; //System.Collections.Generic.List`1[System.Guid]: Tenants
		columns: filterColumn[]; //SampleSinglePageApplication.DataObjects+FilterColumn: FilterColumn
		records: any[]; //System.Object[]: Records
		cultureCode: string; //System.String: CultureCode
		udf01: string; //System.String: udf01
		udf02: string; //System.String: udf02
		udf03: string; //System.String: udf03
		udf04: string; //System.String: udf04
		udf05: string; //System.String: udf05
		udf06: string; //System.String: udf06
		udf07: string; //System.String: udf07
		udf08: string; //System.String: udf08
		udf09: string; //System.String: udf09
		udf10: string; //System.String: udf10
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface filterDepartmentsAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+FilterDepartmentsAuto
		departmentId: string; //System.Nullable`1[System.Guid]: DepartmentId
		departmentName: string; //System.String: DepartmentName
		departmentNameFilterExact: boolean; //System.Boolean: DepartmentNameFilterExact
		departmentNameIncludeInKeyword: boolean; //System.Boolean: DepartmentNameIncludeInKeyword
		activeDirectoryNames: string; //System.String: ActiveDirectoryNames
		activeDirectoryNamesFilterExact: boolean; //System.Boolean: ActiveDirectoryNamesFilterExact
		activeDirectoryNamesIncludeInKeyword: boolean; //System.Boolean: ActiveDirectoryNamesIncludeInKeyword
		enabled: boolean; //System.Nullable`1[System.Boolean]: Enabled
		departmentGroupId: string; //System.Nullable`1[System.Guid]: DepartmentGroupId
		tenantId: string; //System.Guid: TenantId
		executionTime: number; //System.Double: ExecutionTime
		showFilters: boolean; //System.Boolean: ShowFilters
		start: Date; //System.Nullable`1[System.DateTime]: Start
		end: Date; //System.Nullable`1[System.DateTime]: End
		filterId: string; //System.Nullable`1[System.Guid]: FilterId
		keyword: string; //System.String: Keyword
		sort: string; //System.String: Sort
		sortOrder: string; //System.String: SortOrder
		recordsPerPage: number; //System.Int32: RecordsPerPage
		pageCount: number; //System.Int32: PageCount
		recordCount: number; //System.Int32: RecordCount
		page: number; //System.Int32: Page
		export: any[]; //System.Byte[]: Export
		tenants: string[]; //System.Collections.Generic.List`1[System.Guid]: Tenants
		columns: filterColumn[]; //SampleSinglePageApplication.DataObjects+FilterColumn: FilterColumn
		records: any[]; //System.Object[]: Records
		cultureCode: string; //System.String: CultureCode
		udf01: string; //System.String: udf01
		udf02: string; //System.String: udf02
		udf03: string; //System.String: udf03
		udf04: string; //System.String: udf04
		udf05: string; //System.String: udf05
		udf06: string; //System.String: udf06
		udf07: string; //System.String: udf07
		udf08: string; //System.String: udf08
		udf09: string; //System.String: udf09
		udf10: string; //System.String: udf10
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface filterFileStoragesAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+FilterFileStoragesAuto
		fileId: string; //System.Nullable`1[System.Guid]: FileId
		itemId: string; //System.Nullable`1[System.Guid]: ItemId
		fileName: string; //System.String: FileName
		fileNameFilterExact: boolean; //System.Boolean: FileNameFilterExact
		fileNameIncludeInKeyword: boolean; //System.Boolean: FileNameIncludeInKeyword
		extension: string; //System.String: Extension
		extensionFilterExact: boolean; //System.Boolean: ExtensionFilterExact
		extensionIncludeInKeyword: boolean; //System.Boolean: ExtensionIncludeInKeyword
		sourceFileId: string; //System.String: SourceFileId
		sourceFileIdFilterExact: boolean; //System.Boolean: SourceFileIdFilterExact
		sourceFileIdIncludeInKeyword: boolean; //System.Boolean: SourceFileIdIncludeInKeyword
		bytes: number; //System.Nullable`1[System.Int64]: Bytes
		uploadDateStart: Date; //System.Nullable`1[System.DateTime]: UploadDateStart
		uploadDateEnd: Date; //System.Nullable`1[System.DateTime]: UploadDateEnd
		uploadDate: Date; //System.Nullable`1[System.DateTime]: UploadDate
		userId: string; //System.Nullable`1[System.Guid]: UserId
		tenantId: string; //System.Guid: TenantId
		executionTime: number; //System.Double: ExecutionTime
		showFilters: boolean; //System.Boolean: ShowFilters
		start: Date; //System.Nullable`1[System.DateTime]: Start
		end: Date; //System.Nullable`1[System.DateTime]: End
		filterId: string; //System.Nullable`1[System.Guid]: FilterId
		keyword: string; //System.String: Keyword
		sort: string; //System.String: Sort
		sortOrder: string; //System.String: SortOrder
		recordsPerPage: number; //System.Int32: RecordsPerPage
		pageCount: number; //System.Int32: PageCount
		recordCount: number; //System.Int32: RecordCount
		page: number; //System.Int32: Page
		export: any[]; //System.Byte[]: Export
		tenants: string[]; //System.Collections.Generic.List`1[System.Guid]: Tenants
		columns: filterColumn[]; //SampleSinglePageApplication.DataObjects+FilterColumn: FilterColumn
		records: any[]; //System.Object[]: Records
		cultureCode: string; //System.String: CultureCode
		udf01: string; //System.String: udf01
		udf02: string; //System.String: udf02
		udf03: string; //System.String: udf03
		udf04: string; //System.String: udf04
		udf05: string; //System.String: udf05
		udf06: string; //System.String: udf06
		udf07: string; //System.String: udf07
		udf08: string; //System.String: udf08
		udf09: string; //System.String: udf09
		udf10: string; //System.String: udf10
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface filterSettingsAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+FilterSettingsAuto
		settingId: number; //System.Nullable`1[System.Int32]: SettingId
		settingName: string; //System.String: SettingName
		settingNameFilterExact: boolean; //System.Boolean: SettingNameFilterExact
		settingNameIncludeInKeyword: boolean; //System.Boolean: SettingNameIncludeInKeyword
		settingType: string; //System.String: SettingType
		settingTypeFilterExact: boolean; //System.Boolean: SettingTypeFilterExact
		settingTypeIncludeInKeyword: boolean; //System.Boolean: SettingTypeIncludeInKeyword
		settingNotes: string; //System.String: SettingNotes
		settingNotesFilterExact: boolean; //System.Boolean: SettingNotesFilterExact
		settingNotesIncludeInKeyword: boolean; //System.Boolean: SettingNotesIncludeInKeyword
		settingText: string; //System.String: SettingText
		settingTextFilterExact: boolean; //System.Boolean: SettingTextFilterExact
		settingTextIncludeInKeyword: boolean; //System.Boolean: SettingTextIncludeInKeyword
		userId: string; //System.Nullable`1[System.Guid]: UserId
		tenantId: string; //System.Guid: TenantId
		executionTime: number; //System.Double: ExecutionTime
		showFilters: boolean; //System.Boolean: ShowFilters
		start: Date; //System.Nullable`1[System.DateTime]: Start
		end: Date; //System.Nullable`1[System.DateTime]: End
		filterId: string; //System.Nullable`1[System.Guid]: FilterId
		keyword: string; //System.String: Keyword
		sort: string; //System.String: Sort
		sortOrder: string; //System.String: SortOrder
		recordsPerPage: number; //System.Int32: RecordsPerPage
		pageCount: number; //System.Int32: PageCount
		recordCount: number; //System.Int32: RecordCount
		page: number; //System.Int32: Page
		export: any[]; //System.Byte[]: Export
		tenants: string[]; //System.Collections.Generic.List`1[System.Guid]: Tenants
		columns: filterColumn[]; //SampleSinglePageApplication.DataObjects+FilterColumn: FilterColumn
		records: any[]; //System.Object[]: Records
		cultureCode: string; //System.String: CultureCode
		udf01: string; //System.String: udf01
		udf02: string; //System.String: udf02
		udf03: string; //System.String: udf03
		udf04: string; //System.String: udf04
		udf05: string; //System.String: udf05
		udf06: string; //System.String: udf06
		udf07: string; //System.String: udf07
		udf08: string; //System.String: udf08
		udf09: string; //System.String: udf09
		udf10: string; //System.String: udf10
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface filterTenantsAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+FilterTenantsAuto
		name: string; //System.String: Name
		nameFilterExact: boolean; //System.Boolean: NameFilterExact
		nameIncludeInKeyword: boolean; //System.Boolean: NameIncludeInKeyword
		tenantCode: string; //System.String: TenantCode
		tenantCodeFilterExact: boolean; //System.Boolean: TenantCodeFilterExact
		tenantCodeIncludeInKeyword: boolean; //System.Boolean: TenantCodeIncludeInKeyword
		enabled: boolean; //System.Nullable`1[System.Boolean]: Enabled
		tenantId: string; //System.Guid: TenantId
		executionTime: number; //System.Double: ExecutionTime
		showFilters: boolean; //System.Boolean: ShowFilters
		start: Date; //System.Nullable`1[System.DateTime]: Start
		end: Date; //System.Nullable`1[System.DateTime]: End
		filterId: string; //System.Nullable`1[System.Guid]: FilterId
		keyword: string; //System.String: Keyword
		sort: string; //System.String: Sort
		sortOrder: string; //System.String: SortOrder
		recordsPerPage: number; //System.Int32: RecordsPerPage
		pageCount: number; //System.Int32: PageCount
		recordCount: number; //System.Int32: RecordCount
		page: number; //System.Int32: Page
		export: any[]; //System.Byte[]: Export
		tenants: string[]; //System.Collections.Generic.List`1[System.Guid]: Tenants
		columns: filterColumn[]; //SampleSinglePageApplication.DataObjects+FilterColumn: FilterColumn
		records: any[]; //System.Object[]: Records
		cultureCode: string; //System.String: CultureCode
		udf01: string; //System.String: udf01
		udf02: string; //System.String: udf02
		udf03: string; //System.String: udf03
		udf04: string; //System.String: udf04
		udf05: string; //System.String: udf05
		udf06: string; //System.String: udf06
		udf07: string; //System.String: udf07
		udf08: string; //System.String: udf08
		udf09: string; //System.String: udf09
		udf10: string; //System.String: udf10
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface filterUserGroupsAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+FilterUserGroupsAuto
		groupId: string; //System.Nullable`1[System.Guid]: GroupId
		name: string; //System.String: Name
		nameFilterExact: boolean; //System.Boolean: NameFilterExact
		nameIncludeInKeyword: boolean; //System.Boolean: NameIncludeInKeyword
		enabled: boolean; //System.Nullable`1[System.Boolean]: Enabled
		settings: userGroupSettings; //SampleSinglePageApplication.DataObjects+UserGroupSettings: Settings
		tenantId: string; //System.Guid: TenantId
		executionTime: number; //System.Double: ExecutionTime
		showFilters: boolean; //System.Boolean: ShowFilters
		start: Date; //System.Nullable`1[System.DateTime]: Start
		end: Date; //System.Nullable`1[System.DateTime]: End
		filterId: string; //System.Nullable`1[System.Guid]: FilterId
		keyword: string; //System.String: Keyword
		sort: string; //System.String: Sort
		sortOrder: string; //System.String: SortOrder
		recordsPerPage: number; //System.Int32: RecordsPerPage
		pageCount: number; //System.Int32: PageCount
		recordCount: number; //System.Int32: RecordCount
		page: number; //System.Int32: Page
		export: any[]; //System.Byte[]: Export
		tenants: string[]; //System.Collections.Generic.List`1[System.Guid]: Tenants
		columns: filterColumn[]; //SampleSinglePageApplication.DataObjects+FilterColumn: FilterColumn
		records: any[]; //System.Object[]: Records
		cultureCode: string; //System.String: CultureCode
		udf01: string; //System.String: udf01
		udf02: string; //System.String: udf02
		udf03: string; //System.String: udf03
		udf04: string; //System.String: udf04
		udf05: string; //System.String: udf05
		udf06: string; //System.String: udf06
		udf07: string; //System.String: udf07
		udf08: string; //System.String: udf08
		udf09: string; //System.String: udf09
		udf10: string; //System.String: udf10
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface filterUsers extends actionResponseObject { // SampleSinglePageApplication.DataObjects+FilterUsers
		loading: string; //System.String: Loading
		filterDepartments: string[]; //System.Collections.Generic.List`1[System.Guid]: FilterDepartments
		enabled: string; //System.String: Enabled
		admin: string; //System.String: Admin
		udf01: string; //System.String: udf01
		udf02: string; //System.String: udf02
		udf03: string; //System.String: udf03
		udf04: string; //System.String: udf04
		udf05: string; //System.String: udf05
		udf06: string; //System.String: udf06
		udf07: string; //System.String: udf07
		udf08: string; //System.String: udf08
		udf09: string; //System.String: udf09
		udf10: string; //System.String: udf10
		tenantId: string; //System.Guid: TenantId
		executionTime: number; //System.Double: ExecutionTime
		showFilters: boolean; //System.Boolean: ShowFilters
		start: Date; //System.Nullable`1[System.DateTime]: Start
		end: Date; //System.Nullable`1[System.DateTime]: End
		filterId: string; //System.Nullable`1[System.Guid]: FilterId
		keyword: string; //System.String: Keyword
		sort: string; //System.String: Sort
		sortOrder: string; //System.String: SortOrder
		recordsPerPage: number; //System.Int32: RecordsPerPage
		pageCount: number; //System.Int32: PageCount
		recordCount: number; //System.Int32: RecordCount
		page: number; //System.Int32: Page
		export: any[]; //System.Byte[]: Export
		tenants: string[]; //System.Collections.Generic.List`1[System.Guid]: Tenants
		columns: filterColumn[]; //SampleSinglePageApplication.DataObjects+FilterColumn: FilterColumn
		records: any[]; //System.Object[]: Records
		cultureCode: string; //System.String: CultureCode
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface filterUsersAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+FilterUsersAuto
		userId: string; //System.Nullable`1[System.Guid]: UserId
		firstName: string; //System.String: FirstName
		firstNameFilterExact: boolean; //System.Boolean: FirstNameFilterExact
		firstNameIncludeInKeyword: boolean; //System.Boolean: FirstNameIncludeInKeyword
		lastName: string; //System.String: LastName
		lastNameFilterExact: boolean; //System.Boolean: LastNameFilterExact
		lastNameIncludeInKeyword: boolean; //System.Boolean: LastNameIncludeInKeyword
		email: string; //System.String: Email
		emailFilterExact: boolean; //System.Boolean: EmailFilterExact
		emailIncludeInKeyword: boolean; //System.Boolean: EmailIncludeInKeyword
		phone: string; //System.String: Phone
		phoneFilterExact: boolean; //System.Boolean: PhoneFilterExact
		phoneIncludeInKeyword: boolean; //System.Boolean: PhoneIncludeInKeyword
		username: string; //System.String: Username
		usernameFilterExact: boolean; //System.Boolean: UsernameFilterExact
		usernameIncludeInKeyword: boolean; //System.Boolean: UsernameIncludeInKeyword
		employeeId: string; //System.String: EmployeeId
		employeeIdFilterExact: boolean; //System.Boolean: EmployeeIdFilterExact
		employeeIdIncludeInKeyword: boolean; //System.Boolean: EmployeeIdIncludeInKeyword
		departmentId: string; //System.Nullable`1[System.Guid]: DepartmentId
		title: string; //System.String: Title
		titleFilterExact: boolean; //System.Boolean: TitleFilterExact
		titleIncludeInKeyword: boolean; //System.Boolean: TitleIncludeInKeyword
		location: string; //System.String: Location
		locationFilterExact: boolean; //System.Boolean: LocationFilterExact
		locationIncludeInKeyword: boolean; //System.Boolean: LocationIncludeInKeyword
		enabled: boolean; //System.Nullable`1[System.Boolean]: Enabled
		lastLoginStart: Date; //System.Nullable`1[System.DateTime]: LastLoginStart
		lastLoginEnd: Date; //System.Nullable`1[System.DateTime]: LastLoginEnd
		lastLogin: Date; //System.Nullable`1[System.DateTime]: LastLogin
		admin: boolean; //System.Nullable`1[System.Boolean]: Admin
		password: string; //System.String: Password
		passwordFilterExact: boolean; //System.Boolean: PasswordFilterExact
		passwordIncludeInKeyword: boolean; //System.Boolean: PasswordIncludeInKeyword
		preventPasswordChange: boolean; //System.Nullable`1[System.Boolean]: PreventPasswordChange
		failedLoginAttempts: number; //System.Nullable`1[System.Int32]: FailedLoginAttempts
		lastLockoutDateStart: Date; //System.Nullable`1[System.DateTime]: LastLockoutDateStart
		lastLockoutDateEnd: Date; //System.Nullable`1[System.DateTime]: LastLockoutDateEnd
		lastLockoutDate: Date; //System.Nullable`1[System.DateTime]: LastLockoutDate
		source: string; //System.String: Source
		sourceFilterExact: boolean; //System.Boolean: SourceFilterExact
		sourceIncludeInKeyword: boolean; //System.Boolean: SourceIncludeInKeyword
		tenantId: string; //System.Guid: TenantId
		executionTime: number; //System.Double: ExecutionTime
		showFilters: boolean; //System.Boolean: ShowFilters
		start: Date; //System.Nullable`1[System.DateTime]: Start
		end: Date; //System.Nullable`1[System.DateTime]: End
		filterId: string; //System.Nullable`1[System.Guid]: FilterId
		keyword: string; //System.String: Keyword
		sort: string; //System.String: Sort
		sortOrder: string; //System.String: SortOrder
		recordsPerPage: number; //System.Int32: RecordsPerPage
		pageCount: number; //System.Int32: PageCount
		recordCount: number; //System.Int32: RecordCount
		page: number; //System.Int32: Page
		export: any[]; //System.Byte[]: Export
		tenants: string[]; //System.Collections.Generic.List`1[System.Guid]: Tenants
		columns: filterColumn[]; //SampleSinglePageApplication.DataObjects+FilterColumn: FilterColumn
		records: any[]; //System.Object[]: Records
		cultureCode: string; //System.String: CultureCode
		udf01: string; //System.String: udf01
		udf02: string; //System.String: udf02
		udf03: string; //System.String: udf03
		udf04: string; //System.String: udf04
		udf05: string; //System.String: udf05
		udf06: string; //System.String: udf06
		udf07: string; //System.String: udf07
		udf08: string; //System.String: udf08
		udf09: string; //System.String: udf09
		udf10: string; //System.String: udf10
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface language { // SampleSinglePageApplication.DataObjects+Language
		culture: string; //System.String: Culture
		phrases: optionPair[]; //SampleSinglePageApplication.DataObjects+OptionPair: OptionPair
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface listItem extends actionResponseObject { // SampleSinglePageApplication.DataObjects+ListItem
		id: string; //System.Guid: Id
		tenantId: string; //System.Guid: TenantId
		type: string; //System.String: Type
		name: string; //System.String: Name
		sortOrder: number; //System.Int32: SortOrder
		enabled: boolean; //System.Boolean: Enabled
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface mailServerConfig { // SampleSinglePageApplication.DataObjects+MailServerConfig
		server: string; //System.String: Server
		port: number; //System.Int32: Port
		useSSL: boolean; //System.Boolean: UseSSL
		username: string; //System.String: Username
		password: string; //System.String: Password
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface optionPair { // SampleSinglePageApplication.DataObjects+OptionPair
		id: string; //System.String: Id
		value: string; //System.String: Value
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface savedFilterDepartmentGroupsAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+SavedFilterDepartmentGroupsAuto
		description: string; //System.String: Description
		filter: filterDepartmentGroupsAuto; //SampleSinglePageApplication.DataObjects+FilterDepartmentGroupsAuto: Filter
		savedFilterId: string; //System.Guid: SavedFilterId
		tenantId: string; //System.Guid: TenantId
		userId: string; //System.Guid: UserId
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface savedFilterDepartmentsAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+SavedFilterDepartmentsAuto
		description: string; //System.String: Description
		filter: filterDepartmentsAuto; //SampleSinglePageApplication.DataObjects+FilterDepartmentsAuto: Filter
		savedFilterId: string; //System.Guid: SavedFilterId
		tenantId: string; //System.Guid: TenantId
		userId: string; //System.Guid: UserId
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface savedFilterFileStoragesAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+SavedFilterFileStoragesAuto
		description: string; //System.String: Description
		filter: filterFileStoragesAuto; //SampleSinglePageApplication.DataObjects+FilterFileStoragesAuto: Filter
		savedFilterId: string; //System.Guid: SavedFilterId
		tenantId: string; //System.Guid: TenantId
		userId: string; //System.Guid: UserId
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface savedFilterSettingsAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+SavedFilterSettingsAuto
		description: string; //System.String: Description
		filter: filterSettingsAuto; //SampleSinglePageApplication.DataObjects+FilterSettingsAuto: Filter
		savedFilterId: string; //System.Guid: SavedFilterId
		tenantId: string; //System.Guid: TenantId
		userId: string; //System.Guid: UserId
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface savedFilterTenantsAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+SavedFilterTenantsAuto
		description: string; //System.String: Description
		filter: filterTenantsAuto; //SampleSinglePageApplication.DataObjects+FilterTenantsAuto: Filter
		savedFilterId: string; //System.Guid: SavedFilterId
		tenantId: string; //System.Guid: TenantId
		userId: string; //System.Guid: UserId
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface savedFilterUserGroupsAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+SavedFilterUserGroupsAuto
		description: string; //System.String: Description
		filter: filterUserGroupsAuto; //SampleSinglePageApplication.DataObjects+FilterUserGroupsAuto: Filter
		savedFilterId: string; //System.Guid: SavedFilterId
		tenantId: string; //System.Guid: TenantId
		userId: string; //System.Guid: UserId
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface savedFilterUsersAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+SavedFilterUsersAuto
		description: string; //System.String: Description
		filter: filterUsersAuto; //SampleSinglePageApplication.DataObjects+FilterUsersAuto: Filter
		savedFilterId: string; //System.Guid: SavedFilterId
		tenantId: string; //System.Guid: TenantId
		userId: string; //System.Guid: UserId
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface setting extends actionResponseObject { // SampleSinglePageApplication.DataObjects+Setting
		settingId: number; //System.Int32: SettingId
		settingName: string; //System.String: SettingName
		settingType: string; //System.String: SettingType
		settingNotes: string; //System.String: SettingNotes
		settingText: string; //System.String: SettingText
		tenantId: string; //System.Nullable`1[System.Guid]: TenantId
		userId: string; //System.Nullable`1[System.Guid]: UserId
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface signalRUpdate { // SampleSinglePageApplication.DataObjects+SignalRUpdate
		tenantId: string; //System.Nullable`1[System.Guid]: TenantId
		requestId: string; //System.Nullable`1[System.Guid]: RequestId
		itemId: string; //System.String: ItemId
		userId: string; //System.Nullable`1[System.Guid]: UserId
		updateType: server.signalRUpdateType; //SampleSinglePageApplication.DataObjects+SignalRUpdateType: UpdateType
		updateTypeString: string; //System.String: UpdateTypeString
		message: string; //System.String: Message
		object: any; //System.Object: Object
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface simplePost { // SampleSinglePageApplication.DataObjects+SimplePost
		singleItem: string; //System.String: SingleItem
		items: string[]; //System.Collections.Generic.List`1[System.String]: Items
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface simpleResponse { // SampleSinglePageApplication.DataObjects+SimpleResponse
		result: boolean; //System.Boolean: Result
		message: string; //System.String: Message
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface tenant extends actionResponseObject { // SampleSinglePageApplication.DataObjects+Tenant
		tenantId: string; //System.Guid: TenantId
		name: string; //System.String: Name
		tenantCode: string; //System.String: TenantCode
		enabled: boolean; //System.Boolean: Enabled
		departments: department[]; //SampleSinglePageApplication.DataObjects+Department: Department
		departmentGroups: departmentGroup[]; //SampleSinglePageApplication.DataObjects+DepartmentGroup: DepartmentGroup
		tenantSettings: tenantSettings; //SampleSinglePageApplication.DataObjects+TenantSettings: TenantSettings
		udfLabels: udfLabel[]; //SampleSinglePageApplication.DataObjects+udfLabel: udfLabel
		listItems: listItem[]; //SampleSinglePageApplication.DataObjects+ListItem: ListItem
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface tenantList { // SampleSinglePageApplication.DataObjects+TenantList
		tenantId: string; //System.Guid: TenantId
		name: string; //System.String: Name
		tenantCode: string; //System.String: TenantCode
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface tenantSettings { // SampleSinglePageApplication.DataObjects+TenantSettings
		allowUsersToManageAvatars: boolean; //System.Boolean: AllowUsersToManageAvatars
		allowUsersToManageBasicProfileInfo: boolean; //System.Boolean: AllowUsersToManageBasicProfileInfo
		allowUsersToManageBasicProfileInfoElements: string[]; //System.Collections.Generic.List`1[System.String]: AllowUsersToManageBasicProfileInfoElements
		allowUsersToResetPasswordsForLocalLogin: boolean; //System.Boolean: AllowUsersToResetPasswordsForLocalLogin
		allowUsersToSignUpForLocalLogin: boolean; //System.Boolean: AllowUsersToSignUpForLocalLogin
		cookieDomain: string; //System.String: CookieDomain
		customAuthenticationCode: string; //System.String: CustomAuthenticationCode
		customAuthenticationName: string; //System.String: CustomAuthenticationName
		defaultCultureCode: string; //System.String: DefaultCultureCode
		defaultReplyToAddress: string; //System.String: DefaultReplyToAddress
		eitSsoUrl: string; //System.String: EitSsoUrl
		jasonWebTokenKey: string; //System.String: JasonWebTokenKey
		ldapLookupRoot: string; //System.String: LdapLookupRoot
		ldapLookupUsername: string; //System.String: LdapLookupUsername
		ldapLookupPassword: string; //System.String: LdapLookupPassword
		ldapLookupSearchBase: string; //System.String: LdapLookupSearchBase
		ldapLookupLocationAttribute: string; //System.String: LdapLookupLocationAttribute
		ldapLookupPort: number; //System.Int32: LdapLookupPort
		loginOptions: string[]; //System.Collections.Generic.List`1[System.String]: LoginOptions
		moduleHideElements: string[]; //System.Collections.Generic.List`1[System.String]: ModuleHideElements
		workSchedule: workSchedule; //SampleSinglePageApplication.DataObjects+WorkSchedule: WorkSchedule
		requirePreExistingAccountToLogIn: boolean; //System.Boolean: RequirePreExistingAccountToLogIn
		listItems: listItem[]; //SampleSinglePageApplication.DataObjects+ListItem: ListItem
		externalUserDataSources: externalDataSource[]; //SampleSinglePageApplication.DataObjects+ExternalDataSource: ExternalDataSource
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface todoUserAuto extends actionResponseObject { // SampleSinglePageApplication.DataObjects+TodoUserAuto
		savedFiltersDepartmentsAuto: savedFilterDepartmentsAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterDepartmentsAuto: SavedFilterDepartmentsAuto
		savedFiltersDepartmentGroupsAuto: savedFilterDepartmentGroupsAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterDepartmentGroupsAuto: SavedFilterDepartmentGroupsAuto
		savedFiltersFileStoragesAuto: savedFilterFileStoragesAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterFileStoragesAuto: SavedFilterFileStoragesAuto
		savedFiltersSettingsAuto: savedFilterSettingsAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterSettingsAuto: SavedFilterSettingsAuto
		savedFiltersTenantsAuto: savedFilterTenantsAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterTenantsAuto: SavedFilterTenantsAuto
		savedFiltersUsersAuto: savedFilterUsersAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterUsersAuto: SavedFilterUsersAuto
		savedFiltersUserGroupsAuto: savedFilterUserGroupsAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterUserGroupsAuto: SavedFilterUserGroupsAuto
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface udfLabel { // SampleSinglePageApplication.DataObjects+udfLabel
		id: string; //System.Guid: Id
		tenantId: string; //System.Guid: TenantId
		module: string; //System.String: Module
		udf: string; //System.String: udf
		label: string; //System.String: Label
		showColumn: boolean; //System.Boolean: ShowColumn
		showInFilter: boolean; //System.Boolean: ShowInFilter
		includeInSearch: boolean; //System.Boolean: IncludeInSearch
		filterOptions: string[]; //System.Collections.Generic.List`1[System.String]: FilterOptions
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface user extends actionResponseObject { // SampleSinglePageApplication.DataObjects+User
		userId: string; //System.Guid: UserId
		tenantId: string; //System.Guid: TenantId
		firstName: string; //System.String: FirstName
		lastName: string; //System.String: LastName
		displayName: string; //System.String: DisplayName
		email: string; //System.String: Email
		phone: string; //System.String: Phone
		username: string; //System.String: Username
		employeeId: string; //System.String: EmployeeId
		departmentId: string; //System.Nullable`1[System.Guid]: DepartmentId
		departmentName: string; //System.String: DepartmentName
		title: string; //System.String: Title
		location: string; //System.String: Location
		enabled: boolean; //System.Boolean: Enabled
		lastLogin: Date; //System.Nullable`1[System.DateTime]: LastLogin
		admin: boolean; //System.Boolean: Admin
		appAdmin: boolean; //System.Boolean: AppAdmin
		photo: string; //System.Nullable`1[System.Guid]: Photo
		password: string; //System.String: Password
		preventPasswordChange: boolean; //System.Boolean: PreventPasswordChange
		hasLocalPassword: boolean; //System.Boolean: HasLocalPassword
		authToken: string; //System.String: AuthToken
		failedLoginAttempts: number; //System.Int32: FailedLoginAttempts
		lastLockoutDate: Date; //System.Nullable`1[System.DateTime]: LastLockoutDate
		tenants: tenant[]; //SampleSinglePageApplication.DataObjects+Tenant: Tenant
		userTenants: userTenant[]; //SampleSinglePageApplication.DataObjects+UserTenant: UserTenant
		source: string; //System.String: Source
		udf01: string; //System.String: udf01
		udf02: string; //System.String: udf02
		udf03: string; //System.String: udf03
		udf04: string; //System.String: udf04
		udf05: string; //System.String: udf05
		udf06: string; //System.String: udf06
		udf07: string; //System.String: udf07
		udf08: string; //System.String: udf08
		udf09: string; //System.String: udf09
		udf10: string; //System.String: udf10
		savedFiltersDepartmentsAuto: savedFilterDepartmentsAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterDepartmentsAuto: SavedFilterDepartmentsAuto
		savedFiltersDepartmentGroupsAuto: savedFilterDepartmentGroupsAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterDepartmentGroupsAuto: SavedFilterDepartmentGroupsAuto
		savedFiltersFileStoragesAuto: savedFilterFileStoragesAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterFileStoragesAuto: SavedFilterFileStoragesAuto
		savedFiltersSettingsAuto: savedFilterSettingsAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterSettingsAuto: SavedFilterSettingsAuto
		savedFiltersTenantsAuto: savedFilterTenantsAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterTenantsAuto: SavedFilterTenantsAuto
		savedFiltersUsersAuto: savedFilterUsersAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterUsersAuto: SavedFilterUsersAuto
		savedFiltersUserGroupsAuto: savedFilterUserGroupsAuto[]; //SampleSinglePageApplication.DataObjects+SavedFilterUserGroupsAuto: SavedFilterUserGroupsAuto
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface userGroup extends actionResponseObject { // SampleSinglePageApplication.DataObjects+UserGroup
		groupId: string; //System.Guid: GroupId
		tenantId: string; //System.Guid: TenantId
		name: string; //System.String: Name
		enabled: boolean; //System.Boolean: Enabled
		users: string[]; //System.Collections.Generic.List`1[System.Guid]: Users
		settings: userGroupSettings; //SampleSinglePageApplication.DataObjects+UserGroupSettings: Settings
		//actionResponse: booleanResponse; //SampleSinglePageApplication.DataObjects+BooleanResponse: ActionResponse
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface userGroupSettings { // SampleSinglePageApplication.DataObjects+UserGroupSettings
		someSetting: string; //System.String: SomeSetting
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface userPasswordReset { // SampleSinglePageApplication.DataObjects+UserPasswordReset
		userId: string; //System.Guid: UserId
		tenantId: string; //System.Guid: TenantId
		currentPassword: string; //System.String: CurrentPassword
		newPassword: string; //System.String: NewPassword
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface userTenant { // SampleSinglePageApplication.DataObjects+UserTenant
		userId: string; //System.Guid: UserId
		tenantId: string; //System.Guid: TenantId
		tenantCode: string; //System.String: TenantCode
		tenantName: string; //System.String: TenantName
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface versionInfo { // SampleSinglePageApplication.DataObjects+VersionInfo
		released: Date; //System.DateTime: Released
		runningSince: number; //System.Double: RunningSince
		version: string; //System.String: Version
	}

	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	interface workSchedule { // SampleSinglePageApplication.DataObjects+WorkSchedule
		sunday: boolean; //System.Boolean: Sunday
		sundayAllDay: boolean; //System.Boolean: SundayAllDay
		sundayStart: string; //System.String: SundayStart
		sundayEnd: string; //System.String: SundayEnd
		monday: boolean; //System.Boolean: Monday
		mondayAllDay: boolean; //System.Boolean: MondayAllDay
		mondayStart: string; //System.String: MondayStart
		mondayEnd: string; //System.String: MondayEnd
		tuesday: boolean; //System.Boolean: Tuesday
		tuesdayAllDay: boolean; //System.Boolean: TuesdayAllDay
		tuesdayStart: string; //System.String: TuesdayStart
		tuesdayEnd: string; //System.String: TuesdayEnd
		wednesday: boolean; //System.Boolean: Wednesday
		wednesdayAllDay: boolean; //System.Boolean: WednesdayAllDay
		wednesdayStart: string; //System.String: WednesdayStart
		wednesdayEnd: string; //System.String: WednesdayEnd
		thursday: boolean; //System.Boolean: Thursday
		thursdayAllDay: boolean; //System.Boolean: ThursdayAllDay
		thursdayStart: string; //System.String: ThursdayStart
		thursdayEnd: string; //System.String: ThursdayEnd
		friday: boolean; //System.Boolean: Friday
		fridayAllDay: boolean; //System.Boolean: FridayAllDay
		fridayStart: string; //System.String: FridayStart
		fridayEnd: string; //System.String: FridayEnd
		saturday: boolean; //System.Boolean: Saturday
		saturdayAllDay: boolean; //System.Boolean: SaturdayAllDay
		saturdayStart: string; //System.String: SaturdayStart
		saturdayEnd: string; //System.String: SaturdayEnd
	}
}
