/// 
/// Tenant
/// 
/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
///
namespace SampleSinglePageApplication;
public partial interface IDataAccess
{
	DataObjects.Tenant ConvertTenantAuto(SampleSinglePageApplication.EFModels.EFModels.Tenant item);
	Task<DataObjects.BooleanResponse> DeleteTenantAuto(Guid tenantId, bool trySave = true);
	Task<DataObjects.BooleanResponse> DeleteTenantsAuto(List<Guid> tenantIds);
	Task<DataObjects.Tenant> GetTenantAuto(Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<DataObjects.Tenant>>? convert = null);
	Task<DataObjects.Tenant> GetTenantAuto(Guid id,Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<DataObjects.Tenant>>? convert = null);
	Task<List<DataObjects.Tenant>> GetTenantsAuto(List<Guid>? ids = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<DataObjects.Tenant>>? convert = null);
	Task<DataObjects.FilterTenantsAuto> GetTenantsFilteredAuto(DataObjects.FilterTenantsAuto filter, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? overrideFilter = null,Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? additionalFilter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,string, bool ,IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? additionalOrderByAuto = null, Func<DataObjects.Tenant, DataObjects.Tenant> additionalDataAuto = null  );
	Task<DataObjects.Tenant> SaveTenantAuto(DataObjects.Tenant item, bool tryLookup = true, bool trySave = true, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>, DataObjects.Tenant, IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? lookup = null);
	Task<List<DataObjects.Tenant>> SaveTenantsAuto(List<DataObjects.Tenant> items, bool tryLookup = true, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>, DataObjects.Tenant, IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? lookup = null);
	Dictionary<string, string> GetTenantIconAuto();

	Dictionary<string, string> GetTenantLanguageAuto();
}
public partial class DataAccess
{
	public DataObjects.Tenant ConvertTenantAuto(SampleSinglePageApplication.EFModels.EFModels.Tenant item) //SampleSinglePageApplication.DataObjects+Tenant
	{
		var output = new DataObjects.Tenant {
			TenantId = item.TenantId, //OTHER: base(Guid) : actual(Guid)
			Name = item.Name, //OTHER: base(String) : actual(String)
			TenantCode = item.TenantCode, //OTHER: base(String) : actual(String)
			Enabled = item.Enabled, //OTHER: base(Boolean) : actual(Boolean)
			//LIST: base(List`1) : actual(Department)
			//LIST: base(List`1) : actual(DepartmentGroup)
// not on ef model			TenantSettings = item.TenantSettings, //OTHER: base(TenantSettings) : actual(TenantSettings)
			//LIST: base(List`1) : actual(udfLabel)
			//LIST: base(List`1) : actual(ListItem)
		};
		return output;
	}
	public async Task<DataObjects.BooleanResponse> DeleteTenantAuto(Guid tenantId, bool trySave = true) //SampleSinglePageApplication.DataObjects+Tenant
	{
		DataObjects.BooleanResponse output = new DataObjects.BooleanResponse();
		var rec = await data.Tenants.FirstOrDefaultAsync(x => x.TenantId == tenantId);
		if (rec == null) {
			output.Messages.Add("Error Deleting Tenant " + tenantId.ToString() + " - Record No Longer Exists");
		} else {
			data.Tenants.Remove(rec);
			try {
				if (trySave) {
					await data.SaveChangesAsync();
				}
				output.Result = true;
				
				await SignalRUpdate(new DataObjects.SignalRUpdate {
					TenantId = rec.TenantId,
					ItemId = rec.TenantId.ToString(),
					UpdateType = DataObjects.SignalRUpdateType.Tenant,
					Message = "DeletedTenant"
				});
			} catch (Exception ex) {
				output.Messages.Add("Error Deleting Tenant " + tenantId.ToString() + " - " + ex.Message);
			}
		}
		return output;
	}

	public async Task<DataObjects.BooleanResponse> DeleteTenantsAuto(List<Guid> tenantIds)  //SampleSinglePageApplication.DataObjects+Tenant
	{
		DataObjects.BooleanResponse output = new DataObjects.BooleanResponse();
		var recs = await data.Tenants.Where(x => tenantIds.Any(id => id == x.TenantId)).ToListAsync();
		data.Tenants.RemoveRange(recs);
		try {
			await data.SaveChangesAsync();
			output.Result = true;
		} catch (Exception ex) {
			output.Messages.Add("Error Deleting Tenants " + string.Join(",", tenantIds.Select(o => o.ToString())) + " - " + ex.Message);
		}
		return output;
	}

	public async Task<DataObjects.Tenant> GetTenantAuto(Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<DataObjects.Tenant>>? convert = null)  //SampleSinglePageApplication.DataObjects+Tenant
	{
		return await GetTenantAutoPrivate(null, filter, convert);
	}
	public async Task<DataObjects.Tenant> GetTenantAuto(Guid id,Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<DataObjects.Tenant>>? convert = null)  //SampleSinglePageApplication.DataObjects+Tenant
	{
		return await GetTenantAutoPrivate(id, filter, convert);
	}
	private async Task<DataObjects.Tenant> GetTenantAutoPrivate(Guid? id, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<DataObjects.Tenant>>? convert = null)  //SampleSinglePageApplication.DataObjects+Tenant
	{
		DataObjects.Tenant output = new DataObjects.Tenant();
		output.ActionResponse = GetNewActionResponse();
		List<DataObjects.Tenant> records = null;
		if(id != null) {
			records = await GetTenantsAuto(new List<Guid>() { id.Value }, filter, convert );
		} else {
			records = await GetTenantsAuto(null, filter, convert );
		}
		if (records != null && records.Count() > 0) {
			output = records.Single();
			output.ActionResponse.Result = true;
		}
		else {
			output.ActionResponse.Messages.Add("Tenant " + id.ToString() + " Does Not Exist");
		}
		return output;
	}
	public async Task<List<DataObjects.Tenant>> GetTenantsAuto(List<Guid>? ids = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<DataObjects.Tenant>>? convert = null)  //SampleSinglePageApplication.DataObjects+Tenant
	{
		List<DataObjects.Tenant> output = new List<DataObjects.Tenant>();
		IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>? recs = null;
		if (ids != null) {
			recs = data.Tenants.Where(o => ids.Any(id => id == o.TenantId)).AsQueryable();
		} else {
			recs = data.Tenants.AsQueryable();
		}
		if (filter != null) {
			recs = filter(recs);
		}
		if (convert != null) {
			output = await (convert(recs)).ToListAsync();
		} else {
			List<SampleSinglePageApplication.EFModels.EFModels.Tenant> records = await recs.ToListAsync();
			foreach(var o in records) {
				output.Add(ConvertTenantAuto(o));
			}
		}

		return output;
	}
	public async Task<DataObjects.FilterTenantsAuto> GetTenantsFilteredAuto(DataObjects.FilterTenantsAuto filter, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? overrideFilter = null,Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? additionalFilter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>,string, bool ,IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? additionalOrderByAuto = null, Func<DataObjects.Tenant, DataObjects.Tenant> additionalDataAuto = null  )                    
	{
		DataObjects.FilterTenantsAuto output = filter;                                                                       
		output.ActionResponse = GetNewActionResponse();
		output.Records = null;
		
		output.Columns = new List<DataObjects.FilterColumn> {
			new DataObjects.FilterColumn{
				Align = "",                                                                                            
				Label = "Tenant Id",                                                                   
				TipText = "",                                                                                          
				Sortable = true,                                                                                         
				DataElementName = "tenantId",                                                      
				DataType = "string"                                                                                    
			},
			new DataObjects.FilterColumn{
				Align = "",                                                                                            
				Label = "Name",                                                                   
				TipText = "",                                                                                          
				Sortable = true,                                                                                         
				DataElementName = "name",                                                      
				DataType = "string"                                                                                    
			},
			new DataObjects.FilterColumn{
				Align = "",                                                                                            
				Label = "Tenant Code",                                                                   
				TipText = "",                                                                                          
				Sortable = true,                                                                                         
				DataElementName = "tenantCode",                                                      
				DataType = "string"                                                                                    
			},
			new DataObjects.FilterColumn{
				Align = "center",                                                                                      
				Label = "Enabled",                                                                   
				TipText = "",                                                                                          
				Sortable = true,                                                                                         
				DataElementName = "enabled",                                                      
				DataType = "boolean"                                                                                   
			},
		};
	
		IQueryable<Tenant> recs = data.Tenants; 
		recs = recs.Where(x => x.TenantId == output.TenantId);                                               
		if (overrideFilter != null) {
			recs = overrideFilter(recs);
		} else {
			if(additionalFilter != null) {
				recs = additionalFilter(recs);
			}
			// TODO: Guid : TenantId
			if (!string.IsNullOrWhiteSpace(filter.Name)) {
				if (filter.NameFilterExact) {
					recs = recs.Where(o => o.Name == filter.Name); // String : Name
				} else {
					recs = recs.Where(o => o.Name.Contains(filter.Name)); // String : Name
				}
			}
			if (!string.IsNullOrWhiteSpace(filter.TenantCode)) {
				if (filter.TenantCodeFilterExact) {
					recs = recs.Where(o => o.TenantCode == filter.TenantCode); // String : TenantCode
				} else {
					recs = recs.Where(o => o.TenantCode.Contains(filter.TenantCode)); // String : TenantCode
				}
			}
			if (filter.Enabled.HasValue) {
				if( filter.Enabled.Value ) {
					recs = recs.Where(o => o.Enabled == true);
				} else {
					recs = recs.Where(o => o.Enabled == false || o.Enabled == null);
				}
			}
		}

		if (!string.IsNullOrWhiteSpace(filter.Keyword)) {
			recs = recs.Where(o =>
				(filter.NameIncludeInKeyword && o.Name.Contains(string.Empty + filter.Name)) || 
				(filter.TenantCodeIncludeInKeyword && o.TenantCode.Contains(string.Empty + filter.TenantCode))
			);
		}

		bool Ascending = true;
		if (StringOrEmpty(output.SortOrder).ToUpper() == "DESC")
		{
		    Ascending = false;
		}
		
		switch (StringOrEmpty(output.Sort).ToUpper())
		{
			case "TENANTID":                                                        
				if (Ascending)
				{
					recs = recs.OrderBy(x => x.TenantId).ThenBy(x => x.TenantId);     
				}
				else
				{
					recs = recs.OrderByDescending(x => x.TenantId).ThenByDescending(x => x.TenantId);                    
				}
				break;
			case "NAME":                                                        
				if (Ascending)
				{
					recs = recs.OrderBy(x => x.Name).ThenBy(x => x.TenantId);     
				}
				else
				{
					recs = recs.OrderByDescending(x => x.Name).ThenByDescending(x => x.TenantId);                    
				}
				break;
			case "TENANTCODE":                                                        
				if (Ascending)
				{
					recs = recs.OrderBy(x => x.TenantCode).ThenBy(x => x.TenantId);     
				}
				else
				{
					recs = recs.OrderByDescending(x => x.TenantCode).ThenByDescending(x => x.TenantId);                    
				}
				break;
			case "ENABLED":                                                        
				if (Ascending)
				{
					recs = recs.OrderBy(x => x.Enabled).ThenBy(x => x.TenantId);     
				}
				else
				{
					recs = recs.OrderByDescending(x => x.Enabled).ThenByDescending(x => x.TenantId);                    
				}
				break;
		}
		if (additionalOrderByAuto != null) {
			recs = additionalOrderByAuto(recs,StringOrEmpty(output.Sort).ToUpper(),Ascending);
		}
	
		if (recs != null && recs.Count() > 0)
		{
	
			int TotalRecords = recs.Count();
			output.RecordCount = TotalRecords;
	
			if (output.RecordsPerPage > 0)
			{
				// We are filtering records per page
				if (output.RecordsPerPage >= TotalRecords)
					{
					output.Page = 1;
					output.PageCount = 1;
				}
				else
				{
					// Figure out the page count
					if (output.Page < 1) { output.Page = 1; }
					if (output.RecordsPerPage < 1) { output.RecordsPerPage = 25; }
					decimal decPages = (decimal)TotalRecords / (decimal)output.RecordsPerPage;
					decPages = Math.Ceiling(decPages);
					output.PageCount = (int)decPages;
	
					if (output.Page > output.PageCount)
					{
						output.Page = output.PageCount;
					}
	
					if (output.Page > 1)
					{
						recs = recs.Skip((output.Page - 1) * output.RecordsPerPage).Take(output.RecordsPerPage);
					}
					else
					{
						recs = recs.Take(output.RecordsPerPage);
					}
	
				}
			}
	
			// grab the id's now that it is fitered.
			var ids = await recs.Select(o => o.TenantId).ToListAsync();                                                  
			// then use the auto method to read them from the database
			var autoRecs = await this.GetTenantsAuto(ids);                                                               
	
			// loop over the sorted / ordered ids list and build the records output base on that order,
			// not the order returned by the auto recs
			List<DataObjects.Tenant> records = new List<DataObjects.Tenant>();                                           
			foreach (var id in ids)
			{
			    // find the rec out of the autos
			    var autoRec = autoRecs.Single(o => o.TenantId == id);                                                    
			    // add any addtional data we need
			    if (additionalDataAuto != null) {
					autoRec = additionalDataAuto(autoRec);
			    }
			    records.Add(autoRec);
			}
	
			output.Records = records.ToArray();
		}
	
		output.ActionResponse.Result = true;
	
		return output;
	}
	public async Task<DataObjects.Tenant> SaveTenantAuto(DataObjects.Tenant item, bool tryLookup = true, bool trySave = true, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>, DataObjects.Tenant, IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? lookup = null)  //SampleSinglePageApplication.DataObjects+Tenant
	{
		Tenant? rec = null;
		item.ActionResponse = GetNewActionResponse();
		if (tryLookup) {
			if (lookup == null) {
				rec = await data.Tenants.FirstOrDefaultAsync(o => o.TenantId == item.TenantId);
			} else {
				rec = await lookup(data.Tenants.AsQueryable(), item).FirstOrDefaultAsync();
			}
			if(rec != null) {
				 item.TenantId = rec.TenantId;
			}
		}
		var newRecord = false;
		if (rec == null) {
			if (item.TenantId == Guid.Empty){
				rec = new EFModels.EFModels.Tenant();
				item.TenantId = Guid.NewGuid();
				rec.TenantId = item.TenantId;
				newRecord = true;
			} else {
				item.ActionResponse.Messages.Add("Error Saving Tenant " + item.TenantId.ToString() + " - Record No Longer Exists");
				return item;
			}
		}
		item.Name = MaxStringLength(item.Name,200);
		item.TenantCode = MaxStringLength(item.TenantCode,50);

		rec.Name = item.Name; //OTHER: base(String) : actual(String)
		rec.TenantCode = item.TenantCode; //OTHER: base(String) : actual(String)
		rec.Enabled = item.Enabled; //OTHER: base(Boolean) : actual(Boolean)
		//rec.Departments = item.Departments; //OTHER: base(List`1) : actual(Department)
		//rec.DepartmentGroups = item.DepartmentGroups; //OTHER: base(List`1) : actual(DepartmentGroup)
		//rec.TenantSettings = item.TenantSettings; //OTHER: base(TenantSettings) : actual(TenantSettings)
		//rec.udfLabels = item.udfLabels; //OTHER: base(List`1) : actual(udfLabel)
		//rec.ListItems = item.ListItems; //OTHER: base(List`1) : actual(ListItem)
		//rec.ActionResponse = item.ActionResponse; //OTHER: base(BooleanResponse) : actual(BooleanResponse)

		try
		{
			if (newRecord)
			{
				data.Tenants.Add(rec);
			}
			if (trySave) {
				await data.SaveChangesAsync();
				//await SignalRUpdate(new DataObjects.SignalRUpdate
				//{
				//	//TenantId = item.TenantId,
				//	ItemId = item.TenantId.ToString(),
				//	UpdateType = DataObjects.SignalRUpdateType.Tenant,
				//	Message = "TenantSaved",
				//	Object = item
				//});
			}
			item.ActionResponse.Result = true;
		}
		catch (Exception ex)
		{
			item.ActionResponse.Messages.Add("Error Saving Tenant " + item.TenantId.ToString() + " - " + ex.Message);
		}
		return item;
	}
	public async Task<List<DataObjects.Tenant>> SaveTenantsAuto(List<DataObjects.Tenant> items, bool tryLookup = true, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>, DataObjects.Tenant, IQueryable<SampleSinglePageApplication.EFModels.EFModels.Tenant>>? lookup = null)  //SampleSinglePageApplication.DataObjects+Tenant
	{
		List<DataObjects.Tenant> output = new List<DataObjects.Tenant>();
		foreach(var item in items) {
			DataObjects.Tenant saved = await SaveTenantAuto(item, tryLookup, false, lookup);
			if (saved != null && saved.ActionResponse != null && saved.ActionResponse.Result) {
				output.Add(saved);
			}
		}
		await data.SaveChangesAsync();
		return output;
	}

	public Dictionary<string, string> GetTenantIconAuto()
	{
		var output = new Dictionary<string, string>();
		return output;
	}
	public Dictionary<string, string> GetTenantLanguageAuto()
	{
		var output = new Dictionary<string, string>();
		output.Add("Tenant", "Tenant");
		output.Add("Tenant.AddNew", "Add New");
		output.Add("Tenant.Back", "Back");
		output.Add("Tenant.Cancel", "Cancel");
		output.Add("Tenant.CancelDeleteFilter", "Cancel");
		output.Add("Tenant.Clear", "Clear");
		output.Add("Tenant.ConfirmDelete", "Confirm Delete");
		output.Add("Tenant.ConfirmDeleteFilter", "Confirm Delete");
		output.Add("Tenant.Delete", "Delete");
		output.Add("Tenant.DeleteFilter", "Delete Filter");
		output.Add("Tenant.Edit", "Edit");
		output.Add("Tenant.EditTableButton", "Edit");
		output.Add("Tenant.FilterCardView", "Card View");
		output.Add("Tenant.FilterExport", "Export");
		output.Add("Tenant.HidingDetails", "Hiding Details");
		output.Add("Tenant.ListView", "List View");
		output.Add("Tenant.ShowingDetails", "Showing Details");
		output.Add("Tenant.HideFilter", "Hide Filter");
		output.Add("Tenants", "Tenants");
		output.Add("Tenant.Refresh", "Refresh");
		output.Add("Tenant.Save", "Save");
		output.Add("Tenant.SaveFilter", "Save Filter");
		output.Add("Tenant.ShowFilter", "Show Filter");
		output.Add("Tenant.SavedFilters", "Saved Filters");
		output.Add("Tenant.SavedFilterName", "Saved Filter Name");
		output.Add("Tenant.NoRecords", "No Records");
		output.Add("Tenant.Loading", "Loading Tenants, Please Wait");
		output.Add("Tenant.Tenant", "Tenant");
		output.Add("Tenant.TenantStart", "Tenant Start");
		output.Add("Tenant.TenantEnd", "Tenant End");
		output.Add("Tenant.TenantFilterExact", "Exact");
		output.Add("Tenant.TenantIncludeInKeyword", "Keyword");
		output.Add("Tenant.TenantNoRecords", "NoTenantRecords");
		output.Add("Tenant.TenantId","Tenant Id");
		output.Add("Tenant.Name","Name");
		output.Add("Tenant.NameFilterExact","Exact");
		output.Add("Tenant.NameIncludeInKeyword","Keyword");
		output.Add("Tenant.TenantCode","Tenant Code");
		output.Add("Tenant.TenantCodeFilterExact","Exact");
		output.Add("Tenant.TenantCodeIncludeInKeyword","Keyword");
		output.Add("Tenant.Enabled","Enabled");
		return output;
	}

}
