/// 
/// Sample Single Page Applications language autos
/// 
/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
///
namespace SampleSinglePageApplication;
public partial interface IDataAccess 
{
	Dictionary<string, string> GetLanguageAutos();
}

public partial class DataAccess
{
	public Dictionary<string, string> GetLanguageAutos() 
	{
		Dictionary<string, string> output = new Dictionary<string, string>();
		GetDepartmentLanguageAuto().ToList().ForEach(x => output[x.Key] = x.Value);
		GetDepartmentGroupLanguageAuto().ToList().ForEach(x => output[x.Key] = x.Value);
		GetFileStorageLanguageAuto().ToList().ForEach(x => output[x.Key] = x.Value);
		GetSettingLanguageAuto().ToList().ForEach(x => output[x.Key] = x.Value);
		GetTenantLanguageAuto().ToList().ForEach(x => output[x.Key] = x.Value);
		GetUserLanguageAuto().ToList().ForEach(x => output[x.Key] = x.Value);
		GetUserGroupLanguageAuto().ToList().ForEach(x => output[x.Key] = x.Value);

		return output;
	}
}
