/// 
/// DepartmentGroup
/// 
/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
///
namespace SampleSinglePageApplication;
public partial interface IDataAccess
{
	DataObjects.DepartmentGroup ConvertDepartmentGroupAuto(SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup item);
	Task<DataObjects.BooleanResponse> DeleteDepartmentGroupAuto(Guid departmentGroupId, bool trySave = true);
	Task<DataObjects.BooleanResponse> DeleteDepartmentGroupsAuto(List<Guid> departmentGroupIds);
	Task<DataObjects.DepartmentGroup> GetDepartmentGroupAuto(Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<DataObjects.DepartmentGroup>>? convert = null);
	Task<DataObjects.DepartmentGroup> GetDepartmentGroupAuto(Guid id,Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<DataObjects.DepartmentGroup>>? convert = null);
	Task<List<DataObjects.DepartmentGroup>> GetDepartmentGroupsAuto(List<Guid>? ids = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<DataObjects.DepartmentGroup>>? convert = null);
	Task<DataObjects.FilterDepartmentGroupsAuto> GetDepartmentGroupsFilteredAuto(DataObjects.FilterDepartmentGroupsAuto filter, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? overrideFilter = null,Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? additionalFilter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,string, bool ,IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? additionalOrderByAuto = null, Func<DataObjects.DepartmentGroup, DataObjects.DepartmentGroup> additionalDataAuto = null  );
	Task<DataObjects.DepartmentGroup> SaveDepartmentGroupAuto(DataObjects.DepartmentGroup item, bool tryLookup = true, bool trySave = true, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>, DataObjects.DepartmentGroup, IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? lookup = null);
	Task<List<DataObjects.DepartmentGroup>> SaveDepartmentGroupsAuto(List<DataObjects.DepartmentGroup> items, bool tryLookup = true, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>, DataObjects.DepartmentGroup, IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? lookup = null);
	Dictionary<string, string> GetDepartmentGroupIconAuto();

	Dictionary<string, string> GetDepartmentGroupLanguageAuto();
}
public partial class DataAccess
{
	public DataObjects.DepartmentGroup ConvertDepartmentGroupAuto(SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup item) //SampleSinglePageApplication.DataObjects+DepartmentGroup
	{
		var output = new DataObjects.DepartmentGroup {
			DepartmentGroupId = item.DepartmentGroupId, //OTHER: base(Guid) : actual(Guid)
			TenantId = GuidOrEmpty(item.TenantId), //GUID nullable on ef model: base(Guid) : actual(Guid)
			DepartmentGroupName = item.DepartmentGroupName ?? "", //string nullable on ef model: base(String) : actual(String)
		};
		return output;
	}
	public async Task<DataObjects.BooleanResponse> DeleteDepartmentGroupAuto(Guid departmentGroupId, bool trySave = true) //SampleSinglePageApplication.DataObjects+DepartmentGroup
	{
		DataObjects.BooleanResponse output = new DataObjects.BooleanResponse();
		var rec = await data.DepartmentGroups.FirstOrDefaultAsync(x => x.DepartmentGroupId == departmentGroupId);
		if (rec == null) {
			output.Messages.Add("Error Deleting DepartmentGroup " + departmentGroupId.ToString() + " - Record No Longer Exists");
		} else {
			data.DepartmentGroups.Remove(rec);
			try {
				if (trySave) {
					await data.SaveChangesAsync();
				}
				output.Result = true;
				
				await SignalRUpdate(new DataObjects.SignalRUpdate {
					TenantId = rec.TenantId,
					ItemId = rec.DepartmentGroupId.ToString(),
					UpdateType = DataObjects.SignalRUpdateType.DepartmentGroup,
					Message = "DeletedDepartmentGroup"
				});
			} catch (Exception ex) {
				output.Messages.Add("Error Deleting DepartmentGroup " + departmentGroupId.ToString() + " - " + ex.Message);
			}
		}
		return output;
	}

	public async Task<DataObjects.BooleanResponse> DeleteDepartmentGroupsAuto(List<Guid> departmentGroupIds)  //SampleSinglePageApplication.DataObjects+DepartmentGroup
	{
		DataObjects.BooleanResponse output = new DataObjects.BooleanResponse();
		var recs = await data.DepartmentGroups.Where(x => departmentGroupIds.Any(id => id == x.DepartmentGroupId)).ToListAsync();
		data.DepartmentGroups.RemoveRange(recs);
		try {
			await data.SaveChangesAsync();
			output.Result = true;
		} catch (Exception ex) {
			output.Messages.Add("Error Deleting DepartmentGroups " + string.Join(",", departmentGroupIds.Select(o => o.ToString())) + " - " + ex.Message);
		}
		return output;
	}

	public async Task<DataObjects.DepartmentGroup> GetDepartmentGroupAuto(Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<DataObjects.DepartmentGroup>>? convert = null)  //SampleSinglePageApplication.DataObjects+DepartmentGroup
	{
		return await GetDepartmentGroupAutoPrivate(null, filter, convert);
	}
	public async Task<DataObjects.DepartmentGroup> GetDepartmentGroupAuto(Guid id,Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<DataObjects.DepartmentGroup>>? convert = null)  //SampleSinglePageApplication.DataObjects+DepartmentGroup
	{
		return await GetDepartmentGroupAutoPrivate(id, filter, convert);
	}
	private async Task<DataObjects.DepartmentGroup> GetDepartmentGroupAutoPrivate(Guid? id, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<DataObjects.DepartmentGroup>>? convert = null)  //SampleSinglePageApplication.DataObjects+DepartmentGroup
	{
		DataObjects.DepartmentGroup output = new DataObjects.DepartmentGroup();
		output.ActionResponse = GetNewActionResponse();
		List<DataObjects.DepartmentGroup> records = null;
		if(id != null) {
			records = await GetDepartmentGroupsAuto(new List<Guid>() { id.Value }, filter, convert );
		} else {
			records = await GetDepartmentGroupsAuto(null, filter, convert );
		}
		if (records != null && records.Count() > 0) {
			output = records.Single();
			output.ActionResponse.Result = true;
		}
		else {
			output.ActionResponse.Messages.Add("DepartmentGroup " + id.ToString() + " Does Not Exist");
		}
		return output;
	}
	public async Task<List<DataObjects.DepartmentGroup>> GetDepartmentGroupsAuto(List<Guid>? ids = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? filter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<DataObjects.DepartmentGroup>>? convert = null)  //SampleSinglePageApplication.DataObjects+DepartmentGroup
	{
		List<DataObjects.DepartmentGroup> output = new List<DataObjects.DepartmentGroup>();
		IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>? recs = null;
		if (ids != null) {
			recs = data.DepartmentGroups.Where(o => ids.Any(id => id == o.DepartmentGroupId)).AsQueryable();
		} else {
			recs = data.DepartmentGroups.AsQueryable();
		}
		if (filter != null) {
			recs = filter(recs);
		}
		if (convert != null) {
			output = await (convert(recs)).ToListAsync();
		} else {
			List<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup> records = await recs.ToListAsync();
			foreach(var o in records) {
				output.Add(ConvertDepartmentGroupAuto(o));
			}
		}

		return output;
	}
	public async Task<DataObjects.FilterDepartmentGroupsAuto> GetDepartmentGroupsFilteredAuto(DataObjects.FilterDepartmentGroupsAuto filter, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? overrideFilter = null,Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? additionalFilter = null, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>,string, bool ,IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? additionalOrderByAuto = null, Func<DataObjects.DepartmentGroup, DataObjects.DepartmentGroup> additionalDataAuto = null  )                    
	{
		DataObjects.FilterDepartmentGroupsAuto output = filter;                                                                       
		output.ActionResponse = GetNewActionResponse();
		output.Records = null;
		
		output.Columns = new List<DataObjects.FilterColumn> {
			new DataObjects.FilterColumn{
				Align = "",                                                                                            
				Label = "Department Group Id",                                                                   
				TipText = "",                                                                                          
				Sortable = true,                                                                                         
				DataElementName = "departmentGroupId",                                                      
				DataType = "string"                                                                                    
			},
			new DataObjects.FilterColumn{
				Align = "",                                                                                            
				Label = "Tenant Id",                                                                   
				TipText = "",                                                                                          
				Sortable = true,                                                                                         
				DataElementName = "tenantId",                                                      
				DataType = "string"                                                                                    
			},
			new DataObjects.FilterColumn{
				Align = "",                                                                                            
				Label = "Department Group Name",                                                                   
				TipText = "",                                                                                          
				Sortable = true,                                                                                         
				DataElementName = "departmentGroupName",                                                      
				DataType = "string"                                                                                    
			},
		};
	
		IQueryable<DepartmentGroup> recs = data.DepartmentGroups; 
		recs = recs.Where(x => x.TenantId == output.TenantId);                                               
		if (overrideFilter != null) {
			recs = overrideFilter(recs);
		} else {
			if(additionalFilter != null) {
				recs = additionalFilter(recs);
			}
			if (GuidOrEmpty(filter.DepartmentGroupId) != Guid.Empty) {
				recs = recs.Where(o => GuidOrEmpty(o.DepartmentGroupId) == GuidOrEmpty(filter.DepartmentGroupId)); // Guid : DepartmentGroupId
			}
			// TODO: Guid : TenantId
			if (!string.IsNullOrWhiteSpace(filter.DepartmentGroupName)) {
				if (filter.DepartmentGroupNameFilterExact) {
					recs = recs.Where(o => o.DepartmentGroupName == filter.DepartmentGroupName); // String : DepartmentGroupName
				} else {
					recs = recs.Where(o => o.DepartmentGroupName.Contains(filter.DepartmentGroupName)); // String : DepartmentGroupName
				}
			}
		}

		if (!string.IsNullOrWhiteSpace(filter.Keyword)) {
			recs = recs.Where(o =>
				(filter.DepartmentGroupNameIncludeInKeyword && o.DepartmentGroupName.Contains(string.Empty + filter.DepartmentGroupName))
			);
		}

		bool Ascending = true;
		if (StringOrEmpty(output.SortOrder).ToUpper() == "DESC")
		{
		    Ascending = false;
		}
		
		switch (StringOrEmpty(output.Sort).ToUpper())
		{
			case "DEPARTMENTGROUPID":                                                        
				if (Ascending)
				{
					recs = recs.OrderBy(x => x.DepartmentGroupId).ThenBy(x => x.DepartmentGroupId);     
				}
				else
				{
					recs = recs.OrderByDescending(x => x.DepartmentGroupId).ThenByDescending(x => x.DepartmentGroupId);                    
				}
				break;
			case "TENANTID":                                                        
				if (Ascending)
				{
					recs = recs.OrderBy(x => x.TenantId).ThenBy(x => x.DepartmentGroupId);     
				}
				else
				{
					recs = recs.OrderByDescending(x => x.TenantId).ThenByDescending(x => x.DepartmentGroupId);                    
				}
				break;
			case "DEPARTMENTGROUPNAME":                                                        
				if (Ascending)
				{
					recs = recs.OrderBy(x => x.DepartmentGroupName).ThenBy(x => x.DepartmentGroupId);     
				}
				else
				{
					recs = recs.OrderByDescending(x => x.DepartmentGroupName).ThenByDescending(x => x.DepartmentGroupId);                    
				}
				break;
		}
		if (additionalOrderByAuto != null) {
			recs = additionalOrderByAuto(recs,StringOrEmpty(output.Sort).ToUpper(),Ascending);
		}
	
		if (recs != null && recs.Count() > 0)
		{
	
			int TotalRecords = recs.Count();
			output.RecordCount = TotalRecords;
	
			if (output.RecordsPerPage > 0)
			{
				// We are filtering records per page
				if (output.RecordsPerPage >= TotalRecords)
					{
					output.Page = 1;
					output.PageCount = 1;
				}
				else
				{
					// Figure out the page count
					if (output.Page < 1) { output.Page = 1; }
					if (output.RecordsPerPage < 1) { output.RecordsPerPage = 25; }
					decimal decPages = (decimal)TotalRecords / (decimal)output.RecordsPerPage;
					decPages = Math.Ceiling(decPages);
					output.PageCount = (int)decPages;
	
					if (output.Page > output.PageCount)
					{
						output.Page = output.PageCount;
					}
	
					if (output.Page > 1)
					{
						recs = recs.Skip((output.Page - 1) * output.RecordsPerPage).Take(output.RecordsPerPage);
					}
					else
					{
						recs = recs.Take(output.RecordsPerPage);
					}
	
				}
			}
	
			// grab the id's now that it is fitered.
			var ids = await recs.Select(o => o.DepartmentGroupId).ToListAsync();                                                  
			// then use the auto method to read them from the database
			var autoRecs = await this.GetDepartmentGroupsAuto(ids);                                                               
	
			// loop over the sorted / ordered ids list and build the records output base on that order,
			// not the order returned by the auto recs
			List<DataObjects.DepartmentGroup> records = new List<DataObjects.DepartmentGroup>();                                           
			foreach (var id in ids)
			{
			    // find the rec out of the autos
			    var autoRec = autoRecs.Single(o => o.DepartmentGroupId == id);                                                    
			    // add any addtional data we need
			    if (additionalDataAuto != null) {
					autoRec = additionalDataAuto(autoRec);
			    }
			    records.Add(autoRec);
			}
	
			output.Records = records.ToArray();
		}
	
		output.ActionResponse.Result = true;
	
		return output;
	}
	public async Task<DataObjects.DepartmentGroup> SaveDepartmentGroupAuto(DataObjects.DepartmentGroup item, bool tryLookup = true, bool trySave = true, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>, DataObjects.DepartmentGroup, IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? lookup = null)  //SampleSinglePageApplication.DataObjects+DepartmentGroup
	{
		DepartmentGroup? rec = null;
		item.ActionResponse = GetNewActionResponse();
		if (tryLookup) {
			if (lookup == null) {
				rec = await data.DepartmentGroups.FirstOrDefaultAsync(o => o.DepartmentGroupId == item.DepartmentGroupId);
			} else {
				rec = await lookup(data.DepartmentGroups.AsQueryable(), item).FirstOrDefaultAsync();
			}
			if(rec != null) {
				 item.DepartmentGroupId = rec.DepartmentGroupId;
			}
		}
		var newRecord = false;
		if (rec == null) {
			if (item.DepartmentGroupId == Guid.Empty){
				rec = new EFModels.EFModels.DepartmentGroup();
				item.DepartmentGroupId = Guid.NewGuid();
				rec.DepartmentGroupId = item.DepartmentGroupId;
				newRecord = true;
			} else {
				item.ActionResponse.Messages.Add("Error Saving DepartmentGroup " + item.DepartmentGroupId.ToString() + " - Record No Longer Exists");
				return item;
			}
		}
		item.DepartmentGroupName = MaxStringLength(item.DepartmentGroupName,200);

		rec.TenantId = item.TenantId; //OTHER: base(Guid) : actual(Guid)
		rec.DepartmentGroupName = item.DepartmentGroupName; //OTHER: base(String) : actual(String)
		//rec.ActionResponse = item.ActionResponse; //OTHER: base(BooleanResponse) : actual(BooleanResponse)

		try
		{
			if (newRecord)
			{
				data.DepartmentGroups.Add(rec);
			}
			if (trySave) {
				await data.SaveChangesAsync();
				//await SignalRUpdate(new DataObjects.SignalRUpdate
				//{
				//	//TenantId = item.TenantId,
				//	ItemId = item.DepartmentGroupId.ToString(),
				//	UpdateType = DataObjects.SignalRUpdateType.DepartmentGroup,
				//	Message = "DepartmentGroupSaved",
				//	Object = item
				//});
			}
			item.ActionResponse.Result = true;
		}
		catch (Exception ex)
		{
			item.ActionResponse.Messages.Add("Error Saving DepartmentGroup " + item.DepartmentGroupId.ToString() + " - " + ex.Message);
		}
		return item;
	}
	public async Task<List<DataObjects.DepartmentGroup>> SaveDepartmentGroupsAuto(List<DataObjects.DepartmentGroup> items, bool tryLookup = true, Func<IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>, DataObjects.DepartmentGroup, IQueryable<SampleSinglePageApplication.EFModels.EFModels.DepartmentGroup>>? lookup = null)  //SampleSinglePageApplication.DataObjects+DepartmentGroup
	{
		List<DataObjects.DepartmentGroup> output = new List<DataObjects.DepartmentGroup>();
		foreach(var item in items) {
			DataObjects.DepartmentGroup saved = await SaveDepartmentGroupAuto(item, tryLookup, false, lookup);
			if (saved != null && saved.ActionResponse != null && saved.ActionResponse.Result) {
				output.Add(saved);
			}
		}
		await data.SaveChangesAsync();
		return output;
	}

	public Dictionary<string, string> GetDepartmentGroupIconAuto()
	{
		var output = new Dictionary<string, string>();
		return output;
	}
	public Dictionary<string, string> GetDepartmentGroupLanguageAuto()
	{
		var output = new Dictionary<string, string>();
		output.Add("DepartmentGroup", "Department Group");
		output.Add("DepartmentGroup.AddNew", "Add New");
		output.Add("DepartmentGroup.Back", "Back");
		output.Add("DepartmentGroup.Cancel", "Cancel");
		output.Add("DepartmentGroup.CancelDeleteFilter", "Cancel");
		output.Add("DepartmentGroup.Clear", "Clear");
		output.Add("DepartmentGroup.ConfirmDelete", "Confirm Delete");
		output.Add("DepartmentGroup.ConfirmDeleteFilter", "Confirm Delete");
		output.Add("DepartmentGroup.Delete", "Delete");
		output.Add("DepartmentGroup.DeleteFilter", "Delete Filter");
		output.Add("DepartmentGroup.Edit", "Edit");
		output.Add("DepartmentGroup.EditTableButton", "Edit");
		output.Add("DepartmentGroup.FilterCardView", "Card View");
		output.Add("DepartmentGroup.FilterExport", "Export");
		output.Add("DepartmentGroup.HidingDetails", "Hiding Details");
		output.Add("DepartmentGroup.ListView", "List View");
		output.Add("DepartmentGroup.ShowingDetails", "Showing Details");
		output.Add("DepartmentGroup.HideFilter", "Hide Filter");
		output.Add("DepartmentGroups", "Department Groups");
		output.Add("DepartmentGroup.Refresh", "Refresh");
		output.Add("DepartmentGroup.Save", "Save");
		output.Add("DepartmentGroup.SaveFilter", "Save Filter");
		output.Add("DepartmentGroup.ShowFilter", "Show Filter");
		output.Add("DepartmentGroup.SavedFilters", "Saved Filters");
		output.Add("DepartmentGroup.SavedFilterName", "Saved Filter Name");
		output.Add("DepartmentGroup.NoRecords", "No Records");
		output.Add("DepartmentGroup.Loading", "Loading Department Groups, Please Wait");
		output.Add("DepartmentGroup.DepartmentGroup", "Department Group");
		output.Add("DepartmentGroup.DepartmentGroupStart", "Department Group Start");
		output.Add("DepartmentGroup.DepartmentGroupEnd", "Department Group End");
		output.Add("DepartmentGroup.DepartmentGroupFilterExact", "Exact");
		output.Add("DepartmentGroup.DepartmentGroupIncludeInKeyword", "Keyword");
		output.Add("DepartmentGroup.DepartmentGroupNoRecords", "NoDepartmentGroupRecords");
		output.Add("DepartmentGroup.DepartmentGroupId","Department Group Id");
		output.Add("DepartmentGroup.TenantId","Tenant Id");
		output.Add("DepartmentGroup.DepartmentGroupName","Department Group Name");
		output.Add("DepartmentGroup.DepartmentGroupNameFilterExact","Exact");
		output.Add("DepartmentGroup.DepartmentGroupNameIncludeInKeyword","Keyword");
		return output;
	}

}
