/// 
/// UserLookupType
/// 
/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
///
namespace SampleSinglePageApplication;
public partial interface IDataAccess
{
	static DataObjects.UserLookupType? ConvertUserLookupTypeFromString(string? value) => throw new NotImplementedException();
	static string ConvertUserLookupTypeToString(DataObjects.UserLookupType? value) => throw new NotImplementedException();
}

public partial class DataAccess
{
	public static DataObjects.UserLookupType? ConvertUserLookupTypeFromString(string? value)  //SampleSinglePageApplication.DataObjects+UserLookupType
	{
		DataObjects.UserLookupType? output = null;

		if (!string.IsNullOrWhiteSpace(value)) {
			var lowerValue = ("" + value.ToString()).ToLower();
			switch (lowerValue) {
				case "email":
					output = DataObjects.UserLookupType.Email;
					break;
				case "employeeid":
					output = DataObjects.UserLookupType.EmployeeId;
					break;
				case "guid":
					output = DataObjects.UserLookupType.Guid;
					break;
				case "username":
					output = DataObjects.UserLookupType.Username;
					break;
				default:
					break;
			}
		}

		return output;
	}
	///
	/// UserLookupType
	///
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	public static string ConvertUserLookupTypeToString(DataObjects.UserLookupType? value) //SampleSinglePageApplication.DataObjects+UserLookupType
	{
		var output = "";

		if (value != null)
		{
			switch (value)
			{
				case DataObjects.UserLookupType.Email:
					output = "email";
					break;
				case DataObjects.UserLookupType.EmployeeId:
					output = "employeeid";
					break;
				case DataObjects.UserLookupType.Guid:
					output = "guid";
					break;
				case DataObjects.UserLookupType.Username:
					output = "username";
					break;
			default:
				break;
			}
		}

		return output;
	}

}
