using Newtonsoft.Json;
namespace SampleSinglePageApplication;
public partial class DataObjects
{


	/// 
	/// User
	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	public class FilterUsersAuto : Filter
	{
		public Guid? UserId { get; set; }              
		public String? FirstName { get; set; }              
		public bool FirstNameFilterExact { get; set; }              
		public bool FirstNameIncludeInKeyword { get; set; }              
		public String? LastName { get; set; }              
		public bool LastNameFilterExact { get; set; }              
		public bool LastNameIncludeInKeyword { get; set; }              
		public String? Email { get; set; }              
		public bool EmailFilterExact { get; set; }              
		public bool EmailIncludeInKeyword { get; set; }              
		public String? Phone { get; set; }              
		public bool PhoneFilterExact { get; set; }              
		public bool PhoneIncludeInKeyword { get; set; }              
		public String? Username { get; set; }              
		public bool UsernameFilterExact { get; set; }              
		public bool UsernameIncludeInKeyword { get; set; }              
		public String? EmployeeId { get; set; }              
		public bool EmployeeIdFilterExact { get; set; }              
		public bool EmployeeIdIncludeInKeyword { get; set; }              
		public Guid? DepartmentId { get; set; }              
		public String? Title { get; set; }              
		public bool TitleFilterExact { get; set; }              
		public bool TitleIncludeInKeyword { get; set; }              
		public String? Location { get; set; }              
		public bool LocationFilterExact { get; set; }              
		public bool LocationIncludeInKeyword { get; set; }              
		public Boolean? Enabled { get; set; }              
		[JsonConverter(typeof(UTCDateTimeConverter))]
		public DateTime? LastLoginStart { get; set; }
		[JsonConverter(typeof(UTCDateTimeConverter))]
		public DateTime? LastLoginEnd { get; set; }
		[JsonConverter(typeof(UTCDateTimeConverter))]
		public DateTime? LastLogin { get; set; }              
		public Boolean? Admin { get; set; }              
		public String? Password { get; set; }              
		public bool PasswordFilterExact { get; set; }              
		public bool PasswordIncludeInKeyword { get; set; }              
		public Boolean? PreventPasswordChange { get; set; }              
		public Int32? FailedLoginAttempts { get; set; }              
		[JsonConverter(typeof(UTCDateTimeConverter))]
		public DateTime? LastLockoutDateStart { get; set; }
		[JsonConverter(typeof(UTCDateTimeConverter))]
		public DateTime? LastLockoutDateEnd { get; set; }
		[JsonConverter(typeof(UTCDateTimeConverter))]
		public DateTime? LastLockoutDate { get; set; }              
		public String? Source { get; set; }              
		public bool SourceFilterExact { get; set; }              
		public bool SourceIncludeInKeyword { get; set; }              
		// IS NOT ON EF MODEL //public String? DisplayName { get; set; }              
		// IS NOT ON EF MODEL //public String? DepartmentName { get; set; }              
		// IS NOT ON EF MODEL //public Boolean? AppAdmin { get; set; }              
		// IS NOT ON EF MODEL //public Guid? Photo { get; set; }              
		// IS NOT ON EF MODEL //public Boolean? HasLocalPassword { get; set; }              
		// IS NOT ON EF MODEL //public String? AuthToken { get; set; }              
		// IS NOT ON EF MODEL //public Tenant? Tenants { get; set; }              
		// IS NOT ON EF MODEL //public UserTenant? UserTenants { get; set; }              
		// IS NOT ON EF MODEL //public String? udf01 { get; set; }              
		// IS NOT ON EF MODEL //public String? udf02 { get; set; }              
		// IS NOT ON EF MODEL //public String? udf03 { get; set; }              
		// IS NOT ON EF MODEL //public String? udf04 { get; set; }              
		// IS NOT ON EF MODEL //public String? udf05 { get; set; }              
		// IS NOT ON EF MODEL //public String? udf06 { get; set; }              
		// IS NOT ON EF MODEL //public String? udf07 { get; set; }              
		// IS NOT ON EF MODEL //public String? udf08 { get; set; }              
		// IS NOT ON EF MODEL //public String? udf09 { get; set; }              
		// IS NOT ON EF MODEL //public String? udf10 { get; set; }              
		// IS NOT ON EF MODEL //public SavedFilterDepartmentsAuto? SavedFiltersDepartmentsAuto { get; set; }              
		// IS NOT ON EF MODEL //public SavedFilterDepartmentGroupsAuto? SavedFiltersDepartmentGroupsAuto { get; set; }              
		// IS NOT ON EF MODEL //public SavedFilterFileStoragesAuto? SavedFiltersFileStoragesAuto { get; set; }              
		// IS NOT ON EF MODEL //public SavedFilterSettingsAuto? SavedFiltersSettingsAuto { get; set; }              
		// IS NOT ON EF MODEL //public SavedFilterTenantsAuto? SavedFiltersTenantsAuto { get; set; }              
		// IS NOT ON EF MODEL //public SavedFilterUsersAuto? SavedFiltersUsersAuto { get; set; }              
		// IS NOT ON EF MODEL //public SavedFilterUserGroupsAuto? SavedFiltersUserGroupsAuto { get; set; }              
	}

	public class SavedFilterUsersAuto : ActionResponseObject
	{
		public string? Description { get; set; }
		public FilterUsersAuto? Filter { get; set; }
		public Guid SavedFilterId { get; set; }
		public Guid TenantId { get; set; }
		public Guid UserId { get; set; }
	}
}
