using Newtonsoft.Json;
namespace SampleSinglePageApplication;
public partial class DataObjects
{


	/// 
	/// DepartmentGroup
	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	public class FilterDepartmentGroupsAuto : Filter
	{
		public Guid? DepartmentGroupId { get; set; }              
		public String? DepartmentGroupName { get; set; }              
		public bool DepartmentGroupNameFilterExact { get; set; }              
		public bool DepartmentGroupNameIncludeInKeyword { get; set; }              
	}

	public class SavedFilterDepartmentGroupsAuto : ActionResponseObject
	{
		public string? Description { get; set; }
		public FilterDepartmentGroupsAuto? Filter { get; set; }
		public Guid SavedFilterId { get; set; }
		public Guid TenantId { get; set; }
		public Guid UserId { get; set; }
	}
}
