using Newtonsoft.Json;
namespace SampleSinglePageApplication;
public partial class DataObjects
{


	/// 
	/// Tenant
	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	public class FilterTenantsAuto : Filter
	{
		public String? Name { get; set; }              
		public bool NameFilterExact { get; set; }              
		public bool NameIncludeInKeyword { get; set; }              
		public String? TenantCode { get; set; }              
		public bool TenantCodeFilterExact { get; set; }              
		public bool TenantCodeIncludeInKeyword { get; set; }              
		public Boolean? Enabled { get; set; }              
		// IS NOT ON EF MODEL //public Department? Departments { get; set; }              
		// IS NOT ON EF MODEL //public DepartmentGroup? DepartmentGroups { get; set; }              
		// IS NOT ON EF MODEL //public TenantSettings? TenantSettings { get; set; }              
		// IS NOT ON EF MODEL //public udfLabel? udfLabels { get; set; }              
		// IS NOT ON EF MODEL //public ListItem? ListItems { get; set; }              
	}

	public class SavedFilterTenantsAuto : ActionResponseObject
	{
		public string? Description { get; set; }
		public FilterTenantsAuto? Filter { get; set; }
		public Guid SavedFilterId { get; set; }
		public Guid TenantId { get; set; }
		public Guid UserId { get; set; }
	}
}
