using Newtonsoft.Json;
namespace SampleSinglePageApplication;
public partial class DataObjects
{


	/// 
	/// FileStorage
	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	public class FilterFileStoragesAuto : Filter
	{
		public Guid? FileId { get; set; }              
		public Guid? ItemId { get; set; }              
		public String? FileName { get; set; }              
		public bool FileNameFilterExact { get; set; }              
		public bool FileNameIncludeInKeyword { get; set; }              
		public String? Extension { get; set; }              
		public bool ExtensionFilterExact { get; set; }              
		public bool ExtensionIncludeInKeyword { get; set; }              
		public String? SourceFileId { get; set; }              
		public bool SourceFileIdFilterExact { get; set; }              
		public bool SourceFileIdIncludeInKeyword { get; set; }              
		public Int64? Bytes { get; set; }              
		[JsonConverter(typeof(UTCDateTimeConverter))]
		public DateTime? UploadDateStart { get; set; }
		[JsonConverter(typeof(UTCDateTimeConverter))]
		public DateTime? UploadDateEnd { get; set; }
		[JsonConverter(typeof(UTCDateTimeConverter))]
		public DateTime? UploadDate { get; set; }              
		public Guid? UserId { get; set; }              
		// IS NOT ON EF MODEL //public String? Base64value { get; set; }              
	}

	public class SavedFilterFileStoragesAuto : ActionResponseObject
	{
		public string? Description { get; set; }
		public FilterFileStoragesAuto? Filter { get; set; }
		public Guid SavedFilterId { get; set; }
		public Guid TenantId { get; set; }
		public Guid UserId { get; set; }
	}
}
