using Newtonsoft.Json;
namespace SampleSinglePageApplication;
public partial class DataObjects
{


	/// 
	/// UserGroup
	/// 
	/// WARNING: AUTO GENERATED FILE - DO NOT MODIFY BY HAND
	/// GENERATED BY: SampleSinglePageApplication.Transcriber console application.
	///   To regenerate the file, first update the path varibale in the program.cs then run the console app.
	///
	public class FilterUserGroupsAuto : Filter
	{
		public Guid? GroupId { get; set; }              
		public String? Name { get; set; }              
		public bool NameFilterExact { get; set; }              
		public bool NameIncludeInKeyword { get; set; }              
		public Boolean? Enabled { get; set; }              
		public UserGroupSettings? Settings { get; set; }              
		// IS NOT ON EF MODEL //public Guid? Users { get; set; }              
	}

	public class SavedFilterUserGroupsAuto : ActionResponseObject
	{
		public string? Description { get; set; }
		public FilterUserGroupsAuto? Filter { get; set; }
		public Guid SavedFilterId { get; set; }
		public Guid TenantId { get; set; }
		public Guid UserId { get; set; }
	}
}
